from models import *
import numpy as np
from sklearn import preprocessing, feature_selection
from sklearn.svm import SVC
from sklearn.feature_selection import RFE

features = [
	"self.get_rank('RPI')",
	"self.get_rank('SAG')",
	"self.get_rank('POM')",
	"self.get_rank('MOR')",
	"self.fg_mean",
	"self.fg_min",
	"self.fg_max",
	"self.o_fg_mean",
	"self.o_fg_min",
	"self.o_fg_max",
	"self.fg_a_mean",
	"self.fg_a_min",
	"self.fg_a_max",
	"self.o_fg_a_mean",
	"self.o_fg_a_min",
	"self.o_fg_a_max",
	"self.three_fg_mean",
	"self.three_fg_min",
	"self.three_fg_max",
	"self.o_three_fg_mean",
	"self.o_three_fg_min",
	"self.o_three_fg_max",
	"self.three_fg_a_mean",
	"self.three_fg_a_min",
	"self.three_fg_a_max",
	"self.o_three_fg_a_mean",
	"self.o_three_fg_a_min",
	"self.o_three_fg_a_max",
	"self.ft_mean",
	"self.ft_min",
	"self.ft_max",
	"self.o_ft_mean",
	"self.o_ft_min",
	"self.o_ft_max",
	"self.ft_a_mean",
	"self.ft_a_min",
	"self.ft_a_max",
	"self.o_ft_a_mean",
	"self.o_ft_a_min",
	"self.o_ft_a_max",
	"self.pts_mean",
	"self.pts_min",
	"self.pts_max",
	"self.o_pts_mean",
	"self.o_pts_min",
	"self.o_pts_max",
	"self.off_reb_mean",
	"self.off_reb_min",
	"self.off_reb_max",
	"self.o_off_reb_mean",
	"self.o_off_reb_min",
	"self.o_off_reb_max",
	"self.def_reb_mean",
	"self.def_reb_min",
	"self.def_reb_max",
	"self.o_def_reb_mean",
	"self.o_def_reb_min",
	"self.o_def_reb_max",
	"self.reb_mean",
	"self.reb_min",
	"self.reb_max",
	"self.o_reb_mean",
	"self.o_reb_min",
	"self.o_reb_max",
	"self.ast_mean",
	"self.ast_min",
	"self.ast_max",
	"self.o_ast_mean",
	"self.o_ast_min",
	"self.o_ast_max",
	"self.turnovers_mean",
	"self.turnovers_min",
	"self.turnovers_max",
	"self.o_turnovers_mean",
	"self.o_turnovers_min",
	"self.o_turnovers_max",
	"self.steals_mean",
	"self.steals_min",
	"self.steals_max",
	"self.o_steals_mean",
	"self.o_steals_min",
	"self.o_steals_max",
	"self.blocks_mean",
	"self.blocks_min",
	"self.blocks_max",
	"self.o_blocks_mean",
	"self.o_blocks_min",
	"self.o_blocks_max",
	"self.fouls_mean",
	"self.fouls_min",
	"self.fouls_max",
	"self.o_fouls_mean",
	"self.o_fouls_min",
	"self.o_fouls_max",
	"self.offensive_efficiency_mean",
	"self.offensive_efficiency_min",
	"self.offensive_efficiency_max",
	"self.defensive_efficiency_mean",
	"self.defensive_efficiency_min",
	"self.defensive_efficiency_max",
	"self.adj_offensive_efficiency_mean",
	"self.adj_offensive_efficiency_min",
	"self.adj_offensive_efficiency_max",
	"self.adj_defensive_efficiency_mean",
	"self.adj_defensive_efficiency_min",
	"self.adj_defensive_efficiency_max",
	"self.pyth_expectation_mean",
	"self.floor_pct_mean",
	"self.floor_pct_min",
	"self.floor_pct_max",
	"self.field_pct_mean",
	"self.field_pct_min",
	"self.field_pct_max",
	"self.play_pct_mean",
	"self.play_pct_min",
	"self.play_pct_max",
	"self.scoring_possessions_mean",
	"self.scoring_possessions_min",
	"self.scoring_possessions_max",
	"self.plays_mean",
	"self.plays_min",
	"self.plays_max",
	"self.o_floor_pct_mean",
	"self.o_floor_pct_min",
	"self.o_floor_pct_max",
	"self.o_field_pct_mean",
	"self.o_field_pct_min",
	"self.o_field_pct_max",
	"self.o_play_pct_mean",
	"self.o_play_pct_min",
	"self.o_play_pct_max",
	"self.o_play_pct_variance",
	"self.o_scoring_possessions_mean",
	"self.o_scoring_possessions_min",
	"self.o_scoring_possessions_max",
	"self.o_plays_mean",
	"self.o_plays_min",
	"self.o_plays_max",
	"self.effective_fg_pct_mean",
	"self.effective_fg_pct_min",
	"self.effective_fg_pct_max",
	"self.turnover_pct_mean",
	"self.turnover_pct_min",
	"self.turnover_pct_max",
	"self.offensive_reb_pct_mean",
	"self.offensive_reb_pct_min",
	"self.offensive_reb_pct_max",
	"self.ft_rate_mean",
	"self.ft_rate_min",
	"self.ft_rate_max",
	"self.o_effective_fg_pct_mean",
	"self.o_effective_fg_pct_min",
	"self.o_effective_fg_pct_max",
	"self.o_turnover_pct_mean",
	"self.o_turnover_pct_min",
	"self.o_turnover_pct_max",
	"self.o_offensive_reb_pct_mean",
	"self.o_offensive_reb_pct_min",
	"self.o_offensive_reb_pct_max",
	"self.o_ft_rate_mean",
	"self.o_ft_rate_min",
	"self.o_ft_rate_max",
	"self.possessions_mean",
	"self.possessions_min",
	"self.possessions_max",
	"self.fg_pct_mean",
	"self.fg_pct_min",
	"self.fg_pct_max",
	"self.three_fg_pct_mean",
	"self.three_fg_pct_min",
	"self.three_fg_pct_max",
	"self.ft_pct_mean",
	"self.ft_pct_min",
	"self.ft_pct_max",
	"self.o_fg_pct_mean",
	"self.o_fg_pct_min",
	"self.o_fg_pct_max",
	"self.o_three_fg_pct_mean",
	"self.o_three_fg_pct_min",
	"self.o_three_fg_pct_max",
	"self.o_ft_pct_mean",
	"self.o_ft_pct_min",
	"self.o_ft_pct_max",
	"self.win_pct()",
	"self.o_fg_variance",
	"self.ft_a_variance",
	"self.o_ft_variance",
	"self.ft_variance",
	"self.o_three_fg_a_variance",
	"self.three_fg_a_variance",
	"self.o_three_fg_variance",
	"self.fg_a_variance",
	"self.o_fg_a_variance",
	"self.three_fg_variance",
	"self.o_reb_variance",
	"self.reb_variance",
	"self.o_def_reb_variance",
	"self.def_reb_variance",
	"self.o_off_reb_variance",
	"self.off_reb_variance",
	"self.o_pts_variance",
	"self.pts_variance",
	"self.o_ft_a_variance",
	"self.fouls_variance",
	"self.o_blocks_variance",
	"self.blocks_variance",
	"self.o_turnovers_variance",
	"self.turnovers_variance",
	"self.o_ast_variance",
	"self.ast_variance",
	"self.o_steals_variance",
	"self.steals_variance",
	"self.o_fouls_variance",
	"self.fg_variance",
	"self.o_plays_variance",
	"self.o_scoring_possessions_variance",
	"self.o_field_pct_variance",
	"self.o_floor_pct_variance",
	"self.plays_variance",
	"self.scoring_possessions_variance",
	"self.play_pct_variance",
	"self.field_pct_variance",
	"self.floor_pct_variance",
	"self.o_ft_rate_variance",
	"self.o_offensive_reb_pct_variance",
	"self.o_turnover_pct_variance",
	"self.o_effective_fg_pct_variance",
	"self.ft_rate_variance",
	"self.offensive_reb_pct_variance",
	"self.turnover_pct_variance",
	"self.effective_fg_pct_variance",
	"self.possessions_variance",
	"self.o_ft_pct_variance",
	"self.o_three_fg_pct_variance",
	"self.o_fg_pct_variance",
	"self.ft_pct_variance",
	"self.three_fg_pct_variance",
	"self.fg_pct_variance",
	"self.defensive_efficiency_variance",
	"self.offensive_efficiency_variance",
]

#DATA SETUP
games = Game.games_after_with_filter(3, rank_systems=("RPI", "SAG", "POM", "MOR",))
print "%s games returned" % len(games)

data = np.array([g.attributes() for g in games], dtype=np.float)
labels = np.array([g.upset() for g in games])

non_nan_indices = ~np.isnan(data).any(axis=1)
data = data[non_nan_indices]
labels = labels[non_nan_indices]

print "%s usable games returned" % len(data)

#FEATURE SELECTION VIA CLASSIFICATION
f_values, p_values = feature_selection.f_classif(data, labels)

annotated = zip(features, f_values)
sorted_annotated = sorted(annotated, key=lambda x: x[1])

for (feature, f_value) in sorted_annotated:
	print "%s: %s" % (feature, f_value)

print ""

