from models import *
import numpy as np
import csv
from sklearn import svm, preprocessing, tree, decomposition, linear_model
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from pybrain.datasets            import ClassificationDataSet
from pybrain.utilities           import percentError
from pybrain.tools.shortcuts     import buildNetwork
from pybrain.supervised.trainers import BackpropTrainer
from pybrain.structure.modules   import SoftmaxLayer

NAME_MAP = {
	"Abilene Christian" : "Abilene Christian",
	"Air Force Falcons"	: "Air Force",
	"air-force-falcons"	: "Air Force",
	"Air Force"	: "Air Force",
	"Akron Zips"	: "Akron",
	"akron-zips"	: "Akron",
	"Akron"	: "Akron",
	"Alabama Crimson Tide"	: "Alabama",
	"alabama-crimson-tide"	: "Alabama",
	"Alabama"	: "Alabama",
	"Alabama A&M Bulldogs"	: "Alabama A&M",
	"alabama-a&m-bulldogs"	: "Alabama A&M",
	"Alabama A&M"	: "Alabama A&M",
	"Alabama St"	: "Alabama St.",
	"Alabama St. Hornets"	: "Alabama St.",
	"Alabama State"	: "Alabama St.",
	"alabama-state-hornets"	: "Alabama St.",
	"Alabama St."	: "Alabama St.",
	"Albany Great Danes"	: "Albany",
	"Albany NY"	: "Albany",
	"Albany (NY)"	: "Albany",
	"albany-great-danes"	: "Albany",
	"Albany"	: "Albany",
	"Alcorn State"	: "Alcorn St.",
	"Alcorn"	: "Alcorn St.",
	"Alcorn St"	: "Alcorn St.",
	"Alcorn St. Braves"	: "Alcorn St.",
	"alcorn-state-braves"	: "Alcorn St.",
	"Alcorn St."	: "Alcorn St.",
	"American U. Eagles"	: "American",
	"American U."	: "American",
	"American U"	: "American",
	"American Univ"	: "American",
	"american-university-eagles"	: "American",
	"American"	: "American",
	"App St"	: "Appalachian St.",
	"Appalachian St"	: "Appalachian St.",
	"Appalachian St"	: "Appalachian St.",
	"Appalachian St. Mountaineers"	: "Appalachian St.",
	"appalachian-state-mountaineers"	: "Appalachian St.",
	"Appalachian St."	: "Appalachian St.",
	"Arkansas-Little Rock"	: "AR Little Rock",
	"Arkansas Little Rock"	: "AR Little Rock",
	"AR-Little Rock"	: "AR Little Rock",
	"UALR"	: "AR Little Rock",
	"Ark Little Rock"	: "AR Little Rock",
	"Arkansas LR"	: "AR Little Rock",
	"Arkansas-Little Rock Trojans"	: "AR Little Rock",
	"arkansas-little-rock-trojans"	: "AR Little Rock",
	"AR Little Rock"	: "AR Little Rock",
	"Arkansas-Pine Bluff"	: "AR Pine Bluff",
	"Arkansas Pine Bluff"	: "AR Pine Bluff",
	"AR-Pine Bluff"	: "AR Pine Bluff",
	"Ark Pine Bluff"	: "AR Pine Bluff",
	"Ark.-Pine Bluff"	: "AR Pine Bluff",
	"Arkansas-Pine Bluff Golden Lions"	: "AR Pine Bluff",
	"arkansas-pine-bluff-golden-lions"	: "AR Pine Bluff",
	"AR Pine Bluff"	: "AR Pine Bluff",
	"Arizona Wildcats"	: "Arizona",
	"arizona-wildcats"	: "Arizona",
	"Arizona"	: "Arizona",
	"Arizona State"	: "Arizona St.",
	"Arizona St"	: "Arizona St.",
	"Arizona St. Sun Devils"	: "Arizona St.",
	"arizona-state-sun-devils"	: "Arizona St.",
	"Arizona St."	: "Arizona St.",
	"Arkansas Razorbacks"	: "Arkansas",
	"arkansas-razorbacks"	: "Arkansas",
	"Arkansas"	: "Arkansas",
	"Arkansas State"	: "Arkansas St.",
	"Arkansas St"	: "Arkansas St.",
	"Arkansas St. Red Wolves"	: "Arkansas St.",
	"arkansas-state-red-wolves"	: "Arkansas St.",
	"Arkansas St."	: "Arkansas St.",
	"Army Black Knights"	: "Army",
	"army-black-knights"	: "Army",
	"Army"	: "Army",
	"Auburn Tigers"	: "Auburn",
	"auburn-tigers"	: "Auburn",
	"Auburn"	: "Auburn",
	"Austin Peay Governors"	: "Austin Peay",
	"austin-peay-governors"	: "Austin Peay",
	"Austin Peay"	: "Austin Peay",
	"Ball State"	: "Ball St.",
	"Ball St"	: "Ball St.",
	"Ball St. Cardinals"	: "Ball St.",
	"ball-state-cardinals"	: "Ball St.",
	"Ball St."	: "Ball St.",
	"Baylor Bears"	: "Baylor",
	"baylor-bears"	: "Baylor",
	"Baylor"	: "Baylor",
	"Belmont Bruins"	: "Belmont",
	"belmont-bruins"	: "Belmont",
	"Belmont"	: "Belmont",
	"Bethune Cookman"	: "Bethune-Cookman",
	"Bethune-Cookman Wildcats"	: "Bethune-Cookman",
	"Bethune-Cook."	: "Bethune-Cookman",
	"bethune-cookman-wildcats"	: "Bethune-Cookman",
	"Bethune-Cookman"	: "Bethune-Cookman",
	"Binghamton Bearcats"	: "Binghamton",
	"binghamton-bearcats"	: "Binghamton",
	"Binghamton"	: "Binghamton",
	"Birmingham Sou." : "Birmingham Sou.",
	"Birmingham-So." : "Birmingham Sou.",
	"Birmingham Southern" : "Birmingham Sou.",
	"Boise State"	: "Boise St.",
	"Boise St"	: "Boise St.",
	"Boise St. Broncos"	: "Boise St.",
	"boise-state-broncos"	: "Boise St.",
	"Boise St."	: "Boise St.",
	"Boston College Eagles"	: "Boston Coll.",
	"Boston College"	: "Boston Coll.",
	"boston-college-eagles"	: "Boston Coll.",
	"Boston Coll."	: "Boston Coll.",
	"Boston U Terriers"	: "Boston U.",
	"Boston U"	: "Boston U.",
	"Boston Univ"	: "Boston U.",
	"Boston"	: "Boston U.",
	"boston-university-terriers"	: "Boston U.",
	"Boston U."	: "Boston U.",
	"Boston University"	: "Boston U.",
	"Bowling Green Falcons"	: "Bowling Green",
	"bowling-green-falcons"	: "Bowling Green",
	"Bowling Green"	: "Bowling Green",
	"Bradley Braves"	: "Bradley",
	"bradley-braves"	: "Bradley",
	"Bradley"	: "Bradley",
	"Brown Bears"	: "Brown",
	"brown-bears"	: "Brown",
	"Brown"	: "Brown",
	"Bryant Bulldogs"	: "Bryant",
	"Bryant U"	: "Bryant",
	"bryant-university-bulldogs"	: "Bryant",
	"Bryant"	: "Bryant",
	"Bucknell Bison"	: "Bucknell",
	"bucknell-bison"	: "Bucknell",
	"Bucknell"	: "Bucknell",
	"Buffalo Bulls"	: "Buffalo",
	"buffalo-bulls"	: "Buffalo",
	"Buffalo"	: "Buffalo",
	"Butler Bulldogs"	: "Butler",
	"butler-bulldogs"	: "Butler",
	"Butler"	: "Butler",
	"Brigham Young Cougars"	: "BYU",
	"Brigham Young"	: "BYU",
	"brigham-young-cougars"	: "BYU",
	"BYU"	: "BYU",
	"Cal Poly SLO Mustangs"	: "Cal Poly",
	"Cal Poly SLO"	: "Cal Poly",
	"cal-poly-mustangs"	: "Cal Poly",
	"Cal Poly"	: "Cal Poly",
	"California Golden Bears"	: "California",
	"california-golden-bears"	: "California",
	"California"	: "California",
	"Campbell Fighting Camels"	: "Campbell",
	"campbell-fighting-camels"	: "Campbell",
	"Campbell"	: "Campbell",
	"Canisius Golden Griffins"	: "Canisius",
	"canisius-golden-griffins"	: "Canisius",
	"Canisius"	: "Canisius",
	"Cent Michigan"	: "Cent. Michigan",
	"C Michigan"	: "Cent. Michigan",
	"Central Mich."	: "Cent. Michigan",
	"Central Michigan Chippewas"	: "Cent. Michigan",
	"Central Michigan"	: "Cent. Michigan",
	"central-michigan-chippewas"	: "Cent. Michigan",
	"Cent. Michigan"	: "Cent. Michigan",
	"Centenary Gentlemen"	: "Centenary",
	"Centenary"	: "Centenary",
	"Centenary (LA)"	: "Centenary",
	"Central Arkansas Bears"	: "Central Arkansas",
	"Central Ark."	: "Central Arkansas",
	"Cent Arkansas"	: "Central Arkansas",
	"central-arkansas-bears"	: "Central Arkansas",
	"Central Arkansas"	: "Central Arkansas",
	"Central Conn"	: "Central Conn. St.",
	"Central Connecticut"	: "Central Conn. St.",
	"Central Conn. St"	: "Central Conn. St.",
	"Central Conn. St. Blue Devils"	: "Central Conn. St.",
	"Cent Conn St"	: "Central Conn. St.",
	"central-connecticut-state-blue-devils"	: "Central Conn. St.",
	"Central Conn. St."	: "Central Conn. St.",
	"Charleston Cougars"	: "Charleston",
	"College of Charleston"	: "Charleston",
	"Coll Charleston"	: "Charleston",
	"Col Charleston"	: "Charleston",
	"Col. of Charleston"	: "Charleston",
	"charleston-cougars"	: "Charleston",
	"Charleston"	: "Charleston",
	"Charl Southern"	: "Charleston Sou.",
	"Charleston So."	: "Charleston Sou.",
	"Charleston Sou"	: "Charleston Sou.",
	"Charleston So"	: "Charleston Sou.",
	"Charleston Southern Buccaneers"	: "Charleston Sou.",
	"Charleston Southern"	: "Charleston Sou.",
	"CSU"	: "Charleston Sou.",
	"charleston-southern-buccaneers"	: "Charleston Sou.",
	"Charleston Sou."	: "Charleston Sou.",
	"Charlotte 49ers"	: "Charlotte",
	"charlotte-49ers"	: "Charlotte",
	"Charlotte"	: "Charlotte",
	"Chattanooga Mocs"	: "Chattanooga",
	"Tennessee Chat"	: "Chattanooga",
	"chattanooga-mocs"	: "Chattanooga",
	"Chattanooga"	: "Chattanooga",
	"Chicago State"	: "Chicago St.",
	"Chicago St"	: "Chicago St.",
	"Chicago St. Cougars"	: "Chicago St.",
	"chicago-state-cougars"	: "Chicago St.",
	"Chicago St."	: "Chicago St.",
	"Cincinnati Bearcats"	: "Cincinnati",
	"cincinnati-bearcats"	: "Cincinnati",
	"Cincinnati"	: "Cincinnati",
	"Citadel Bulldogs"	: "Citadel",
	"The Citadel"	: "Citadel",
	"citadel-bulldogs"	: "Citadel",
	"Citadel"	: "Citadel",
	"Clemson Tigers"	: "Clemson",
	"clemson-tigers"	: "Clemson",
	"Clemson"	: "Clemson",
	"Cleveland State"	: "Cleveland St.",
	"Cleveland St"	: "Cleveland St.",
	"Cleveland St. Vikings"	: "Cleveland St.",
	"cleveland-state-vikings"	: "Cleveland St.",
	"Cleveland St."	: "Cleveland St.",
	"Coastal Carolina Chanticleers"	: "Coastal Carolina",
	"Coast Carolina"	: "Coastal Carolina",
	"Coastal Caro."	: "Coastal Carolina",
	"Coastal Car"	: "Coastal Carolina",
	"coastal-carolina-chanticleers"	: "Coastal Carolina",
	"Coastal Carolina"	: "Coastal Carolina",
	"Colgate Raiders"	: "Colgate",
	"colgate-raiders"	: "Colgate",
	"Colgate"	: "Colgate",
	"Colorado Buffaloes"	: "Colorado",
	"colorado-buffaloes"	: "Colorado",
	"Colorado"	: "Colorado",
	"Colorado St"	: "Colorado St.",
	"Colorado St. Rams"	: "Colorado St.",
	"Colorado State"	: "Colorado St.",
	"colorado-state-rams"	: "Colorado St.",
	"Colorado St."	: "Colorado St.",
	"Columbia Lions"	: "Columbia",
	"columbia-lions"	: "Columbia",
	"Columbia"	: "Columbia",
	"Connecticut Huskies"	: "Connecticut",
	"connecticut-huskies"	: "Connecticut",
	"Connecticut"	: "Connecticut",
	"UConn"	: "Connecticut",
	"Coppin State"	: "Coppin St.",
	"Coppin St"	: "Coppin St.",
	"Coppin St. Eagles"	: "Coppin St.",
	"coppin-state-eagles"	: "Coppin St.",
	"Coppin St."	: "Coppin St.",
	"Cornell Big Red"	: "Cornell",
	"cornell-big-red"	: "Cornell",
	"Cornell"	: "Cornell",
	"Creighton Bluejays"	: "Creighton",
	"creighton-bluejays"	: "Creighton",
	"Creighton"	: "Creighton",
	"Cal. State - Bakersfield"	: "CSU Bakersfield",
	"Cal St. Bakersfield"	: "CSU Bakersfield",
	"Bakersfield"	: "CSU Bakersfield",
	"CS Bakersfield"	: "CSU Bakersfield",
	"Cal. State - Bakersfield Roadrunners"	: "CSU Bakersfield",
	"cal-state-bakersfield-roadrunners"	: "CSU Bakersfield",
	"CSU Bakersfield"	: "CSU Bakersfield",
	"CS Fullerton"	: "CSU Fullerton",
	"Cal St. Fullerton Titans"	: "CSU Fullerton",
	"Cal St. Fullerton"	: "CSU Fullerton",
	"cal-state-fullerton-titans"	: "CSU Fullerton",
	"CSU Fullerton"	: "CSU Fullerton",
	"CS Northridge"	: "CSU Northridge",
	"Cal St. Northridge"	: "CSU Northridge",
	"CSU Northridge Matadors"	: "CSU Northridge",
	"cal-state-northridge-matadors"	: "CSU Northridge",
	"CSU Northridge"	: "CSU Northridge",
	"Dartmouth Big Green"	: "Dartmouth",
	"dartmouth-big-green"	: "Dartmouth",
	"Dartmouth"	: "Dartmouth",
	"Davidson Wildcats"	: "Davidson",
	"davidson-wildcats"	: "Davidson",
	"Davidson"	: "Davidson",
	"Dayton Flyers"	: "Dayton",
	"dayton-flyers"	: "Dayton",
	"Dayton"	: "Dayton",
	"Delaware Blue Hens"	: "Delaware",
	"delaware-fightin-blue-hens"	: "Delaware",
	"Delaware"	: "Delaware",
	"Delaware State"	: "Delaware St.",
	"Delaware St"	: "Delaware St.",
	"Delaware State Hornets"	: "Delaware St.",
	"delaware-state-hornets"	: "Delaware St.",
	"Delaware St."	: "Delaware St.",
	"Denver Pioneers"	: "Denver",
	"denver-pioneers"	: "Denver",
	"Denver"	: "Denver",
	"DePaul Blue Demons"	: "DePaul",
	"depaul-blue-demons"	: "DePaul",
	"DePaul"	: "DePaul",
	"Detroit Titans"	: "Detroit",
	"detroit-titans"	: "Detroit",
	"Detroit"	: "Detroit",
	"Drake Bulldogs"	: "Drake",
	"drake-bulldogs"	: "Drake",
	"Drake"	: "Drake",
	"Drexel Dragons"	: "Drexel",
	"drexel-dragons"	: "Drexel",
	"Drexel"	: "Drexel",
	"Duke Blue Devils"	: "Duke",
	"duke-blue-devils"	: "Duke",
	"Duke"	: "Duke",
	"Duquesne Dukes"	: "Duquesne",
	"duquesne-dukes"	: "Duquesne",
	"Duquesne"	: "Duquesne",
	"East Tenn St"	: "E. Tennessee St.",
	"East Tenn. St."	: "E. Tennessee St.",
	"East Tennessee St."	: "E. Tennessee St.",
	"E Tennessee St"	: "E. Tennessee St.",
	"E Tennessee St."	: "E. Tennessee St.",
	"E. Tennessee St"	: "E. Tennessee St.",
	"ETSU"	: "E. Tennessee St.",
	"East Tennessee St. Buccaneers"	: "E. Tennessee St.",
	"east-tennessee-state-buccaneers"	: "E. Tennessee St.",
	"E. Tennessee St."	: "E. Tennessee St.",
	"East Carolina Pirates"	: "East Carolina",
	"East Carolina Pirates"	: "East Carolina",
	"east-carolina-pirates"	: "East Carolina",
	"East Carolina"	: "East Carolina",
	"Eastern Michigan Eagles"	: "East. Michigan",
	"Eastern Michigan"	: "East. Michigan",
	"E Michigan"	: "East. Michigan",
	"Eastern Mich."	: "East. Michigan",
	"eastern-michigan-eagles"	: "East. Michigan",
	"East. Michigan"	: "East. Michigan",
	"Eastern Illinois Panthers"	: "Eastern Illinois",
	"E Illinois"	: "Eastern Illinois",
	"Eastern Ill."	: "Eastern Illinois",
	"eastern-illinois-panthers"	: "Eastern Illinois",
	"Eastern Illinois"	: "Eastern Illinois",
	"Eastern Kentucky Colonels"	: "Eastern Kentucky",
	"E Kentucky"	: "Eastern Kentucky",
	"Eastern Ky."	: "Eastern Kentucky",
	"eastern-kentucky-colonels"	: "Eastern Kentucky",
	"Eastern Kentucky"	: "Eastern Kentucky",
	"E. Washington"	: "Eastern Wash.",
	"E Washington"	: "Eastern Wash.",
	"Eastern Washington"	: "Eastern Wash.",
	"Eastern Washington Eagles"	: "Eastern Wash.",
	"eastern-washington-eagles"	: "Eastern Wash.",
	"Eastern Wash."	: "Eastern Wash.",
	"Elon University"	: "Elon",
	"Elon University Phoenix"	: "Elon",
	"elon-phoenix"	: "Elon",
	"Elon"	: "Elon",
	"Evansville Purple Aces"	: "Evansville",
	"evansville-aces"	: "Evansville",
	"Evansville"	: "Evansville",
	"Fairleigh Dickinson"	: "Fair. Dickinson",
	"Fair Dickinson"	: "Fair. Dickinson",
	"F Dickinson"	: "Fair. Dickinson",
	"Fairleigh Dickinson Knights"	: "Fair. Dickinson",
	"fairleigh-dickinson-knights"	: "Fair. Dickinson",
	"Fair. Dickinson"	: "Fair. Dickinson",
	"Fairfield Stags"	: "Fairfield",
	"fairfield-stags"	: "Fairfield",
	"Fairfield"	: "Fairfield",
	"FL Gulf Coast"	: "Fla Gulf Coast",
	"FGCU"	: "Fla Gulf Coast",
	"Florida Gulf Coast"	: "Fla Gulf Coast",
	"Florida Gulf Coast Eagles"	: "Fla Gulf Coast",
	"Fla Gulf Coast"	: "Fla Gulf Coast",
	"Florida Gators"	: "Florida",
	"florida-gators"	: "Florida",
	"Florida"	: "Florida",
	"Florida A&M Rattlers"	: "Florida A&M",
	"florida-a&m-rattlers"	: "Florida A&M",
	"Florida A&M"	: "Florida A&M",
	"FL Atlantic"	: "Florida Atlantic",
	"Fla. Atlantic"	: "Florida Atlantic",
	"Fla Atlantic"	: "Florida Atlantic",
	"Florida Atl"	: "Florida Atlantic",
	"Florida Atlantic Owls"	: "Florida Atlantic",
	"florida-atlantic-owls"	: "Florida Atlantic",
	"Florida Atlantic"	: "Florida Atlantic",
	"FIU"	: "Florida Intl.",
	"Florida International Golden Panthers"	: "Florida Intl.",
	"Florida International"	: "Florida Intl.",
	"Florida Intl"	: "Florida Intl.",
	"Florida Int"	: "Florida Intl.",
	"florida-international-golden-panthers"	: "Florida Intl.",
	"Florida Intl."	: "Florida Intl.",
	"Florida St"	: "Florida St.",
	"Florida State"	: "Florida St.",
	"Florida St. Seminoles"	: "Florida St.",
	"florida-state-seminoles"	: "Florida St.",
	"Florida St."	: "Florida St.",
	"Fordham Rams"	: "Fordham",
	"fordham-rams"	: "Fordham",
	"Fordham"	: "Fordham",
	"Fresno State"	: "Fresno St.",
	"Fresno St"	: "Fresno St.",
	"Fresno St. Bulldogs"	: "Fresno St.",
	"fresno-state-bulldogs"	: "Fresno St.",
	"Fresno St."	: "Fresno St.",
	"Furman Paladins"	: "Furman",
	"furman-paladins"	: "Furman",
	"Furman"	: "Furman",
	"Gardner Webb"	: "Gardner-Webb",
	"Gardner-Webb Runnin' Bulldogs"	: "Gardner-Webb",
	"gardner-webb-runnin'-bulldogs"	: "Gardner-Webb",
	"Gardner-Webb"	: "Gardner-Webb",
	"GW"	: "Geo. Washington",
	"Geo Washington"	: "Geo. Washington",
	"G. Washington"	: "Geo. Washington",
	"G Washington"	: "Geo. Washington",
	"George Washington"	: "Geo. Washington",
	"George Washington Colonials"	: "Geo. Washington",
	"george-washington-colonials"	: "Geo. Washington",
	"Geo. Washington"	: "Geo. Washington",
	"George Mason Patriots"	: "George Mason",
	"george-mason-patriots"	: "George Mason",
	"George Mason"	: "George Mason",
	"Georgetown Hoyas"	: "Georgetown",
	"georgetown-hoyas"	: "Georgetown",
	"Georgetown"	: "Georgetown",
	"Georgia Bulldogs"	: "Georgia",
	"georgia-bulldogs"	: "Georgia",
	"Georgia"	: "Georgia",
	"Ga. Southern"	: "Georgia Southern",
	"Ga Southern"	: "Georgia Southern",
	"G Southern"	: "Georgia Southern",
	"Georgia Southern Eagles"	: "Georgia Southern",
	"georgia-southern-eagles"	: "Georgia Southern",
	"Georgia Southern"	: "Georgia Southern",
	"Georgia St Panthers"	: "Georgia St.",
	"Georgia State"	: "Georgia St.",
	"Georgia St"	: "Georgia St.",
	"georgia-state-panthers"	: "Georgia St.",
	"Georgia St."	: "Georgia St.",
	"Georgia Tech Yellow Jackets"	: "Georgia Tech",
	"georgia-tech-yellow-jackets"	: "Georgia Tech",
	"Georgia Tech"	: "Georgia Tech",
	"Gonzaga Bulldogs"	: "Gonzaga",
	"gonzaga-bulldogs"	: "Gonzaga",
	"Gonzaga"	: "Gonzaga",
	"Grambling St"	: "Grambling St.",
	"Grambling State"	: "Grambling St.",
	"Grambling State Tigers"	: "Grambling St.",
	"Grambling"	: "Grambling St.",
	"grambling-state-tigers"	: "Grambling St.",
	"Grambling St."	: "Grambling St.",
	"Grand Canyon" : "Grand Canyon",
	"Hampton Pirates"	: "Hampton",
	"hampton-pirates"	: "Hampton",
	"Hampton"	: "Hampton",
	"Hartford Hawks"	: "Hartford",
	"hartford-hawks"	: "Hartford",
	"Hartford"	: "Hartford",
	"Harvard Crimson"	: "Harvard",
	"harvard-crimson"	: "Harvard",
	"Harvard"	: "Harvard",
	"Hawaii Warriors"	: "Hawaii",
	"hawaii-warriors"	: "Hawaii",
	"Hawaii"	: "Hawaii",
	"High Point Panthers"	: "High Point",
	"high-point-panthers"	: "High Point",
	"High Point"	: "High Point",
	"Hofstra Pride"	: "Hofstra",
	"hofstra-pride"	: "Hofstra",
	"Hofstra"	: "Hofstra",
	"Holy Cross Crusaders"	: "Holy Cross",
	"holy-cross-crusaders"	: "Holy Cross",
	"Holy Cross"	: "Holy Cross",
	"Houston Cougars"	: "Houston",
	"houston-cougars"	: "Houston",
	"Houston"	: "Houston",
	"Houston Baptist Huskies"	: "Houston Baptist",
	"Houston Bap"	: "Houston Baptist",
	"houston-baptist-huskies"	: "Houston Baptist",
	"Houston Baptist"	: "Houston Baptist",
	"Howard Bison"	: "Howard",
	"howard-bison"	: "Howard",
	"Howard"	: "Howard",
	"Idaho U"	: "Idaho",
	"Idaho Vandals"	: "Idaho",
	"idaho-vandals"	: "Idaho",
	"Idaho"	: "Idaho",
	"Idaho State"	: "Idaho St.",
	"Idaho St"	: "Idaho St.",
	"Idaho State Bengals"	: "Idaho St.",
	"idaho-state-bengals"	: "Idaho St.",
	"Idaho St."	: "Idaho St.",
	"UIC"	: "Ill. Chicago",
	"Ill.-Chicago"	: "Ill. Chicago",
	"Illinois-Chicago"	: "Ill. Chicago",
	"Illinois Chicago"	: "Ill. Chicago",
	"IL Chicago"	: "Ill. Chicago",
	"IL-Chicago"	: "Ill. Chicago",
	"Illinois-Chicago Flames"	: "Ill. Chicago",
	"illinois-chicago-flames"	: "Ill. Chicago",
	"Ill. Chicago"	: "Ill. Chicago",
	"Illinois Fighting Illini"	: "Illinois",
	"illinois-fighting-illini"	: "Illinois",
	"Illinois"	: "Illinois",
	"Illinois St"	: "Illinois St.",
	"Illinois St. Redbirds"	: "Illinois St.",
	"Illinois State"	: "Illinois St.",
	"illinois-state-redbirds"	: "Illinois St.",
	"Illinois St."	: "Illinois St.",
	"Incarnate Word" : "Incarnate Word",
	"Indiana Hoosiers"	: "Indiana",
	"indiana-hoosiers"	: "Indiana",
	"Indiana"	: "Indiana",
	"Indiana State"	: "Indiana St.",
	"Indiana St"	: "Indiana St.",
	"Indiana St. Sycamores"	: "Indiana St.",
	"indiana-state-sycamores"	: "Indiana St.",
	"Indiana St."	: "Indiana St.",
	"Iona Gaels"	: "Iona",
	"iona-gaels"	: "Iona",
	"Iona"	: "Iona",
	"Iowa Hawkeyes"	: "Iowa",
	"iowa-hawkeyes"	: "Iowa",
	"Iowa"	: "Iowa",
	"Iowa St"	: "Iowa St.",
	"Iowa St. Cyclones"	: "Iowa St.",
	"Iowa State"	: "Iowa St.",
	"iowa-state-cyclones"	: "Iowa St.",
	"Iowa St."	: "Iowa St.",
	"IUPU - Ft. Wayne Mastodons"	: "IPFW",
	"IUPU - Ft. Wayne"	: "IPFW",
	"ipfw-mastodons"	: "IPFW",
	"IPFW"	: "IPFW",
	"Indiana - Purdue"	: "IUPUI",
	"Indiana - Purdue Jaguars"	: "IUPUI",
	"iupui-jaguars"	: "IUPUI",
	"IUPUI"	: "IUPUI",
	"jackson-state-tigers"	: "Jackson St.",
	"Jackson St"	: "Jackson St",
	"Jackson State"	: "Jackson St.",
	"Jackson St"	: "Jackson St.",
	"Jackson State Tigers"	: "Jackson St.",
	"Jackson St."	: "Jackson St.",
	"Jacksonville Dolphins"	: "Jacksonville",
	"jacksonville-dolphins"	: "Jacksonville",
	"Jacksonville"	: "Jacksonville",
	"Jacksonville St"	: "Jacksonville St.",
	"Jacksonville St. Gamecocks"	: "Jacksonville St.",
	"jacksonville-state-gamecocks"	: "Jacksonville St.",
	"Jacksonville St."	: "Jacksonville St.",
	"James Madison Dukes"	: "James Madison",
	"james-madison-dukes"	: "James Madison",
	"James Madison"	: "James Madison",
	"Kansas Jayhawks"	: "Kansas",
	"kansas-jayhawks"	: "Kansas",
	"Kansas"	: "Kansas",
	"Kansas St"	: "Kansas St.",
	"Kansas State"	: "Kansas St.",
	"Kansas St. Wildcats"	: "Kansas St.",
	"kansas-state-wildcats"	: "Kansas St.",
	"Kansas St."	: "Kansas St.",
	"Kennesaw"	: "Kennesaw St.",
	"Kennesaw State"	: "Kennesaw St.",
	"Kennesaw St"	: "Kennesaw St.",
	"Kennesaw St. Fighting Owls"	: "Kennesaw St.",
	"kennesaw-state-owls"	: "Kennesaw St.",
	"Kennesaw St."	: "Kennesaw St.",
	"Kent"	: "Kent St.",
	"Kent St"	: "Kent St.",
	"Kent State"	: "Kent St.",
	"Kent St. Golden Flashes"	: "Kent St.",
	"kent-state-golden-flashes"	: "Kent St.",
	"Kent St."	: "Kent St.",
	"Kentucky Wildcats"	: "Kentucky",
	"kentucky-wildcats"	: "Kentucky",
	"Kentucky"	: "Kentucky",
	"LA-Lafayette"	: "LA Lafayette",
	"Louisiana Lafayette"	: "LA Lafayette",
	"La.-Lafayette"	: "LA Lafayette",
	"Louisiana-Lafayette"	: "LA Lafayette",
	"Louisiana-Lafayette Ragin' Cajuns"	: "LA Lafayette",
	"UL Lafayette"	: "LA Lafayette",
	"ULL"	: "LA Lafayette",
	"louisiana-lafayette-ragin'-cajuns"	: "LA Lafayette",
	"LA Lafayette"	: "LA Lafayette",
	"LA-Monroe"	: "LA Monroe",
	"Louisiana Monroe"	: "LA Monroe",
	"La.-Monroe"	: "LA Monroe",
	"Louisiana-Monroe"	: "LA Monroe",
	"Louisiana-Monroe Warhawks"	: "LA Monroe",
	"UL Monroe"	: "LA Monroe",
	"ULM"	: "LA Monroe",
	"louisiana-monroe-warhawks"	: "LA Monroe",
	"LA Monroe"	: "LA Monroe",
	"La Salle Explorers"	: "La Salle",
	"LaSalle"	: "La Salle",
	"la-salle-explorers"	: "La Salle",
	"La Salle"	: "La Salle",
	"Lafayette Leopards"	: "Lafayette",
	"lafayette-leopards"	: "Lafayette",
	"Lafayette"	: "Lafayette",
	"Lamar Cardinals"	: "Lamar",
	"lamar-cardinals"	: "Lamar",
	"Lamar"	: "Lamar",
	"Lehigh Mountain Hawks"	: "Lehigh",
	"lehigh-mountain-hawks"	: "Lehigh",
	"Lehigh"	: "Lehigh",
	"Liberty Flames"	: "Liberty",
	"liberty-flames"	: "Liberty",
	"Liberty"	: "Liberty",
	"Lipscomb Bison"	: "Lipscomb",
	"lipscomb-bisons"	: "Lipscomb",
	"Lipscomb"	: "Lipscomb",
	"Long Beach St"	: "Long Beach St.",
	"Long Beach St. 49ers"	: "Long Beach St.",
	"Long Beach State"	: "Long Beach St.",
	"long-beach-state-49ers"	: "Long Beach St.",
	"Long Beach St."	: "Long Beach St.",
	"LIU Brooklyn Blackbirds"	: "Long Island",
	"LIU Brooklyn"	: "Long Island",
	"liu-brooklyn-blackbirds"	: "Long Island",
	"Long Island"	: "Long Island",
	"Longwood Lancers"	: "Longwood",
	"longwood-lancers"	: "Longwood",
	"Longwood"	: "Longwood",
	"Louisiana College Wildcats"	: "Louisiana Tech",
	"Louisiana Tech Bulldogs"	: "Louisiana Tech",
	"louisiana-tech-bulldogs"	: "Louisiana Tech",
	"Louisiana Tech"	: "Louisiana Tech",
	"Louisville Cardinals"	: "Louisville",
	"louisville-cardinals"	: "Louisville",
	"Louisville"	: "Louisville",
	"Loyola MD"	: "Loyola (MD)",
	"Loyola Maryland"	: "Loyola (MD)",
	"Loyola-Maryland"	: "Loyola (MD)",
	"Loyola-Maryland Greyhounds"	: "Loyola (MD)",
	"loyola-(md-greyhounds)"	: "Loyola (MD)",
	"Loyola (MD)"	: "Loyola (MD)",
	"Loyola-Chicago"	: "Loyola Chicago",
	"Loyola-Chicago Ramblers"	: "Loyola Chicago",
	"loyola-(il-ramblers)"	: "Loyola Chicago",
	"Loyola (IL)"	: "Loyola Chicago",
	"Loyola Chicago"	: "Loyola Chicago",
	"Loyola Marymount Lions"	: "Loyola Marymount",
	"Loyola Mary"	: "Loyola Marymount",
	"Loy Marymount"	: "Loyola Marymount",
	"loyola-marymount-lions"	: "Loyola Marymount",
	"Loyola Marymount"	: "Loyola Marymount",
	"Louisiana State"	: "LSU",
	"Louisiana State Tigers"	: "LSU",
	"lsu-tigers"	: "LSU",
	"LSU"	: "LSU",
	"Maine Black Bears"	: "Maine",
	"maine-black-bears"	: "Maine",
	"Maine"	: "Maine",
	"Manhattan Jaspers"	: "Manhattan",
	"manhattan-jaspers"	: "Manhattan",
	"Manhattan"	: "Manhattan",
	"Marian College Knights"	: "Marist",
	"Marist Red Foxes"	: "Marist",
	"marist-red-foxes"	: "Marist",
	"Marist"	: "Marist",
	"Marquette Golden Eagles"	: "Marquette",
	"marquette-golden-eagles"	: "Marquette",
	"Marquette"	: "Marquette",
	"Marshall Thundering Herd"	: "Marshall",
	"marshall-thundering-herd"	: "Marshall",
	"Marshall"	: "Marshall",
	"Maryland Terrapins"	: "Maryland",
	"maryland-terrapins"	: "Maryland",
	"Maryland"	: "Maryland",
	"UMass Lowell"	: "Mass Lowell",
	"MA Lowell"	: "Mass Lowell",
	"Mass Lowell"	: "Mass Lowell",
	"Massachusetts Minutemen"	: "Massachusetts",
	"Massachusetts Minutemen"	: "Massachusetts",
	"massachusetts-minutemen"	: "Massachusetts",
	"Massachusetts"	: "Massachusetts",
	"McNeese State"	: "McNeese St.",
	"McNeese St"	: "McNeese St.",
	"McNeese St. Cowboys"	: "McNeese St.",
	"mcneese-state-cowboys"	: "McNeese St.",
	"McNeese St."	: "McNeese St.",
	"Maryland - E. Shore"	: "MD Eastern Shore",
	"Maryland Eastern Shore"	: "MD Eastern Shore",
	"UMES"	: "MD Eastern Shore",
	"MD-E Shore"	: "MD Eastern Shore",
	"MD E Shore"	: "MD Eastern Shore",
	"Md.-East. Shore"	: "MD Eastern Shore",
	"Maryland - E. Shore Hawks"	: "MD Eastern Shore",
	"maryland-eastern-shore-hawks"	: "MD Eastern Shore",
	"MD Eastern Shore"	: "MD Eastern Shore",
	"Memphis Tigers"	: "Memphis",
	"Memphis U"	: "Memphis",
	"memphis-tigers"	: "Memphis",
	"Memphis"	: "Memphis",
	"Mercer Bears"	: "Mercer",
	"mercer-bears"	: "Mercer",
	"Mercer"	: "Mercer",
	"Miami FL"	: "Miami (FL)",
	"Miami Florida"	: "Miami (FL)",
	"Miami-Florida"	: "Miami (FL)",
	"Miami - Florida"	: "Miami (FL)",
	"Miami-Florida Hurricanes"	: "Miami (FL)",
	"miami-(fl-hurricanes)"	: "Miami (FL)",
	"Miami (FL)"	: "Miami (FL)",
	"Miami (OH Red Hawks)"	: "Miami (OH)",
	"Miami Ohio"	: "Miami (OH)",
	"Miami OH"	: "Miami (OH)",
	"miami-(oh-redhawks)"	: "Miami (OH)",
	"Miami (OH)"	: "Miami (OH)",
	"Michigan Wolverines"	: "Michigan",
	"michigan-wolverines"	: "Michigan",
	"Michigan"	: "Michigan",
	"Michigan St Spartans"	: "Michigan St.",
	"Michigan St"	: "Michigan St.",
	"Michigan State"	: "Michigan St.",
	"michigan-state-spartans"	: "Michigan St.",
	"Michigan St."	: "Michigan St.",
	"middle-tennessee-blue-raiders"	: "Middle Tenn. St.",
	"Middle Tenn St."	: "Middle Tenn. St.",
	"Middle Tenn."	: "Middle Tenn. St.",
	"Middle Tennessee"	: "Middle Tenn. St.",
	"Middle Tennessee St."	: "Middle Tenn. St.",
	"Middle Tenn St"	: "Middle Tenn. St.",
	"Middle Tenn St."	: "Middle Tenn. St.",
	"Middle Tenn. St"	: "Middle Tenn. St.",
	"Mid Tennessee"	: "Middle Tenn. St.",
	"Middle Tennessee St. Blue Raiders"	: "Middle Tenn. St.",
	"Middle Tenn. St."	: "Middle Tenn. St.",
	"Minnesota Golden Gophers"	: "Minnesota",
	"minnesota-golden-gophers"	: "Minnesota",
	"Minnesota"	: "Minnesota",
	"Mississippi Valley State"	: "Miss. Valley St.",
	"Miss Valley St"	: "Miss. Valley St.",
	"Mississippi Val."	: "Miss. Valley St.",
	"Miss Valley St"	: "Miss. Valley St.",
	"Miss Valley St."	: "Miss. Valley St.",
	"Miss. Valley St"	: "Miss. Valley St.",
	"Mississippi Valley St."	: "Miss. Valley St.",
	"MS Valley St"	: "Miss. Valley St.",
	"Mississippi Valley State Delta Devils"	: "Miss. Valley St.",
	"mississippi-valley-state-delta-devils"	: "Miss. Valley St.",
	"Miss. Valley St."	: "Miss. Valley St.",
	"Ole Miss"	: "Mississippi",
	"Mississippi Rebels"	: "Mississippi",
	"ole-miss-rebels"	: "Mississippi",
	"Mississippi"	: "Mississippi",
	"Mississippi St"	: "Mississippi St.",
	"Mississippi St. Bulldogs"	: "Mississippi St.",
	"Miss. St"	: "Mississippi St.",
	"Miss. St."	: "Mississippi St.",
	"mississippi-state-bulldogs"	: "Mississippi St.",
	"Mississippi St."	: "Mississippi St.",
	"Missouri Tigers"	: "Missouri",
	"missouri-tigers"	: "Missouri",
	"Missouri"	: "Missouri",
	"Missouri State"	: "Missouri St.",
	"Missouri St"	: "Missouri St.",
	"Missouri St"	: "Missouri St.",
	"Missouri St. Bears"	: "Missouri St.",
	"missouri-state-bears"	: "Missouri St.",
	"Missouri St."	: "Missouri St.",
	"Missouri KC"	: "Mo. Kansas City",
	"UMKC Kangaroos"	: "Mo. Kansas City",
	"UMKC"	: "Mo. Kansas City",
	"umkc-kangaroos"	: "Mo. Kansas City",
	"Mo. Kansas City"	: "Mo. Kansas City",
	"Monmouth-NJ Hawks"	: "Monmouth",
	"Monmouth NJ"	: "Monmouth",
	"Monmouth-NJ"	: "Monmouth",
	"monmouth-hawks"	: "Monmouth",
	"Monmouth"	: "Monmouth",
	"Montana Grizzlies"	: "Montana",
	"montana-grizzlies"	: "Montana",
	"Montana"	: "Montana",
	"Montana State"	: "Montana St.",
	"Montana St"	: "Montana St.",
	"Montana St. Bobcats"	: "Montana St.",
	"montana-state-bobcats"	: "Montana St.",
	"Montana St."	: "Montana St.",
	"Morehead State"	: "Morehead St.",
	"Morehead St"	: "Morehead St.",
	"Morehead St. Eagles"	: "Morehead St.",
	"morehead-state-eagles"	: "Morehead St.",
	"Morehead St."	: "Morehead St.",
	"Morgan State"	: "Morgan St.",
	"Morgan St"	: "Morgan St.",
	"Morgan St. Bears"	: "Morgan St.",
	"morgan-state-bears"	: "Morgan St.",
	"Morgan St."	: "Morgan St.",
	"Morris Brown" : "Morris Brown",
	"Mt St Mary's"	: "Mount St. Mary's",
	"Mount St Mary's"	: "Mount St. Mary's",
	"Mt. St. Mary's"	: "Mount St. Mary's",
	"Mount St Marys"	: "Mount St. Mary's",
	"Mount St. Mary's Mountaineers"	: "Mount St. Mary's",
	"mount-st.-mary's-mountaineers"	: "Mount St. Mary's",
	"Mount St. Mary's"	: "Mount St. Mary's",
	"Murray St"	: "Murray St.",
	"Murray St. Racers"	: "Murray St.",
	"Murray State"	: "Murray St.",
	"murray-state-racers"	: "Murray St.",
	"Murray St."	: "Murray St.",
	"No.Carolina A&T"	: "N.C. A&T",
	"N. Carolina A&T"	: "N.C. A&T",
	"N Carolina A&T"	: "N.C. A&T",
	"No.Carolina A&T Aggies"	: "N.C. A&T",
	"NC A&T"	: "N.C. A&T",
	"north-carolina-a&t-aggies"	: "N.C. A&T",
	"N.C. A&T"	: "N.C. A&T",
	"North Carolina A&T"	: "N.C. A&T",
	"UNC Asheville"	: "N.C. Asheville",
	"UNC-Asheville"	: "N.C. Asheville",
	"NC Asheville"	: "N.C. Asheville",
	"NC-Asheville Bulldogs"	: "N.C. Asheville",
	"unc-asheville-bulldogs"	: "N.C. Asheville",
	"N.C. Asheville"	: "N.C. Asheville",
	"North Carolina Central"	: "N.C. Central",
	"NC Central"	: "N.C. Central",
	"North Carolina Central Eagles"	: "N.C. Central",
	"N Carolina Cent"	: "N.C. Central",
	"north-carolina-central-eagles"	: "N.C. Central",
	"N.C. Central"	: "N.C. Central",
	"Greensboro"	: "N.C. Greensboro",
	"UNC Greensboro"	: "N.C. Greensboro",
	"NC Greensboro"	: "N.C. Greensboro",
	"NC-Greensboro"	: "N.C. Greensboro",
	"NC Greensboro"	: "N.C. Greensboro",
	"NC-Greensboro Spartans"	: "N.C. Greensboro",
	"unc-greensboro-spartans"	: "N.C. Greensboro",
	"N.C. Greensboro"	: "N.C. Greensboro",
	"North Carolina State"	: "N.C. State",
	"NC St"	: "N.C. State",
	"North Carolina St."	: "N.C. State",
	"NC St."	: "N.C. State",
	"NC State"	: "N.C. State",
	"N Carolina St."	: "N.C. State",
	"N.C. State Wolfpack"	: "N.C. State",
	"north-carolina-state-wolfpack"	: "N.C. State",
	"N.C. State"	: "N.C. State",
	"UNC Wilmington"	: "N.C. Wilmington",
	"UNC-Wilmington"	: "N.C. Wilmington",
	"NC-Wilmington"	: "N.C. Wilmington",
	"NC Wilmington"	: "N.C. Wilmington",
	"NC-Wilmington Seahawks"	: "N.C. Wilmington",
	"north-carolina-wilmington-seahawks"	: "N.C. Wilmington",
	"N.C. Wilmington"	: "N.C. Wilmington",
	"NJIT"	: "N.J.I.T.",
	"New Jersey Tech Highlanders"	: "N.J.I.T.",
	"n.j.i.t.-highlanders"	: "N.J.I.T.",
	"N.J.I.T."	: "N.J.I.T.",
	"Navy Midshipmen"	: "Navy",
	"Navy"	: "Navy",
	"Nebraska Cornhuskers"	: "Nebraska",
	"nebraska-cornhuskers"	: "Nebraska",
	"Nebraska"	: "Nebraska",
	"Nebraska-Omaha"	: "Nebraska Omaha",
	"Omaha"	: "Nebraska Omaha",
	"NE Omaha"	: "Nebraska Omaha",
	"nebraska-omaha-mavericks"	: "Nebraska Omaha",
	"Nebraska Omaha"	: "Nebraska Omaha",
	"Nevada Wolf Pack"	: "Nevada",
	"nevada-wolf-pack"	: "Nevada",
	"Nevada"	: "Nevada",
	"New Hampshire Wildcats"	: "New Hampshire",
	"new-hampshire-wildcats"	: "New Hampshire",
	"New Hampshire"	: "New Hampshire",
	"New Mexico Lobos"	: "New Mexico",
	"new-mexico-lobos"	: "New Mexico",
	"New Mexico"	: "New Mexico",
	"New Mexico St"	: "New Mexico St.",
	"New Mexico St. Aggies"	: "New Mexico St.",
	"New Mexico State"	: "New Mexico St.",
	"new-mexico-state-aggies"	: "New Mexico St.",
	"New Mexico St."	: "New Mexico St.",
	"New Orleans Privateers"	: "New Orleans",
	"new-orleans-privateers"	: "New Orleans",
	"New Orleans"	: "New Orleans",
	"Niagara Purple Eagles"	: "Niagara",
	"niagara-purple-eagles"	: "Niagara",
	"Niagara"	: "Niagara",
	"Nicholls"	: "Nicholls St.",
	"Nicholls State"	: "Nicholls St.",
	"Nicholls St"	: "Nicholls St.",
	"Nicholls State Colonels"	: "Nicholls St.",
	"nicholls-state-colonels"	: "Nicholls St.",
	"Nicholls St."	: "Nicholls St.",
	"Norfolk St"	: "Norfolk St.",
	"Norfolk St"	: "Norfolk St.",
	"Norfolk State"	: "Norfolk St.",
	"Norfolk State Spartans"	: "Norfolk St.",
	"norfolk-state-spartans"	: "Norfolk St.",
	"Norfolk St."	: "Norfolk St.",
	"North Carolina Tar Heels"	: "North Carolina",
	"north-carolina-tar-heels"	: "North Carolina",
	"North Carolina"	: "North Carolina",
	"North Dakota Fighting Sioux"	: "North Dakota",
	"north-dakota-"	: "North Dakota",
	"North Dakota"	: "North Dakota",
	"N Dakota St"	: "North Dakota St.",
	"N Dakota St."	: "North Dakota St.",
	"North Dakota State"	: "North Dakota St.",
	"NDSU"	: "North Dakota St.",
	"North Dakota St"	: "North Dakota St.",
	"North Dakota State Bison"	: "North Dakota St.",
	"north-dakota-state-bison"	: "North Dakota St.",
	"North Dakota St."	: "North Dakota St.",
	"North Florida Osprey"	: "North Florida",
	"north-florida-ospreys"	: "North Florida",
	"North Florida"	: "North Florida",
	"North Texas Mean Green Eagles"	: "North Texas",
	"north-texas-mean-green"	: "North Texas",
	"North Texas"	: "North Texas",
	"Northeastern Huskies"	: "Northeastern",
	"northeastern-huskies"	: "Northeastern",
	"Northeastern"	: "Northeastern",
	"Northern Arizona Lumberjacks"	: "Northern Arizona",
	"N Arizona"	: "Northern Arizona",
	"Northern Ariz."	: "Northern Arizona",
	"Northern New Mexico Eagles"	: "Northern Arizona",
	"northern-arizona-lumberjacks"	: "Northern Arizona",
	"Northern Arizona"	: "Northern Arizona",
	"No. Colorado"	: "Northern Colorado",
	"N Colorado"	: "Northern Colorado",
	"Northern Colorado Bears"	: "Northern Colorado",
	"northern-colorado-bears"	: "Northern Colorado",
	"Northern Colorado"	: "Northern Colorado",
	"Northern Colo."	: "Northern Colorado",
	"No Illinois"	: "Northern Illinois",
	"Northern Ill."	: "Northern Illinois",
	"N Illinois"	: "Northern Illinois",
	"Northern Illinois Huskies"	: "Northern Illinois",
	"northern-illinois-huskies"	: "Northern Illinois",
	"Northern Illinois"	: "Northern Illinois",
	"Northern Iowa Panthers"	: "Northern Iowa",
	"UNI"	: "Northern Iowa",
	"northern-iowa-panthers"	: "Northern Iowa",
	"Northern Iowa"	: "Northern Iowa",
	"North. Kentucky"	: "Northern Kentucky",
	"N Kentucky"	: "Northern Kentucky",
	"Northern Ky."	: "Northern Kentucky",
	"NKU"	: "Northern Kentucky",
	"northern-kentucky-norse"	: "Northern Kentucky",
	"Northern Kentucky"	: "Northern Kentucky",
	"Northwestern Wildcats"	: "Northwestern",
	"northwestern-wildcats"	: "Northwestern",
	"Northwestern"	: "Northwestern",
	"Northwestern St"	: "Northwestern St.",
	"Northwestern St. Demons"	: "Northwestern St.",
	"NW St"	: "Northwestern St.",
	"Northwestern LA"	: "Northwestern St.",
	"northwestern-state-demons"	: "Northwestern St.",
	"Northwestern St."	: "Northwestern St.",
	"Notre Dame Fighting Irish"	: "Notre Dame",
	"notre-dame-fighting-irish"	: "Notre Dame",
	"Notre Dame"	: "Notre Dame",
	"Oakland Golden Grizzlies"	: "Oakland",
	"oakland-golden-grizzlies"	: "Oakland",
	"Oakland"	: "Oakland",
	"Ohio Bobcats"	: "Ohio",
	"ohio-bobcats"	: "Ohio",
	"Ohio"	: "Ohio",
	"Ohio St Buckeyes"	: "Ohio St.",
	"Ohio St"	: "Ohio St.",
	"Ohio State"	: "Ohio St.",
	"ohio-state-buckeyes"	: "Ohio St.",
	"Ohio St."	: "Ohio St.",
	"Oklahoma Sooners"	: "Oklahoma",
	"oklahoma-sooners"	: "Oklahoma",
	"Oklahoma"	: "Oklahoma",
	"Oklahoma State"	: "Oklahoma St.",
	"Oklahoma St"	: "Oklahoma St.",
	"Oklahoma St. Cowboys"	: "Oklahoma St.",
	"oklahoma-state-cowboys"	: "Oklahoma St.",
	"Oklahoma St."	: "Oklahoma St.",
	"Old Dominion Monarchs"	: "Old Dominion",
	"old-dominion-monarchs"	: "Old Dominion",
	"Old Dominion"	: "Old Dominion",
	"Oral Roberts Golden Eagles"	: "Oral Roberts",
	"oral-roberts-golden-eagles"	: "Oral Roberts",
	"Oral Roberts"	: "Oral Roberts",
	"Oregon Ducks"	: "Oregon",
	"oregon-ducks"	: "Oregon",
	"Oregon"	: "Oregon",
	"Oregon State"	: "Oregon St.",
	"Oregon St"	: "Oregon St.",
	"Oregon St. Beavers"	: "Oregon St.",
	"oregon-state-beavers"	: "Oregon St.",
	"Oregon St."	: "Oregon St.",
	"Pacific Tigers"	: "Pacific",
	"pacific-tigers"	: "Pacific",
	"Pacific"	: "Pacific",
	"Penn State"	: "Penn St.",
	"Penn St"	: "Penn St.",
	"Penn St. Nittany Lions"	: "Penn St.",
	"penn-state-nittany-lions"	: "Penn St.",
	"Penn St."	: "Penn St.",
	"Penn"	: "Pennsylvania",
	"Pennsylvania Quakers"	: "Pennsylvania",
	"pennsylvania-quakers"	: "Pennsylvania",
	"Pennsylvania"	: "Pennsylvania",
	"Pepperdine Waves"	: "Pepperdine",
	"pepperdine-waves"	: "Pepperdine",
	"Pepperdine"	: "Pepperdine",
	"Pittsburgh Panthers"	: "Pittsburgh",
	"pittsburgh-panthers"	: "Pittsburgh",
	"Pittsburgh"	: "Pittsburgh",
	"Portland Pilots"	: "Portland",
	"Portland U"	: "Portland",
	"portland-pilots"	: "Portland",
	"Portland"	: "Portland",
	"Portland State"	: "Portland St.",
	"Portland St"	: "Portland St.",
	"Portland St. Vikings"	: "Portland St.",
	"portland-state-vikings"	: "Portland St.",
	"Portland St."	: "Portland St.",
	"PV A&M"	: "Prairie View A&M",
	"Prairie View A&M Panthers"	: "Prairie View A&M",
	"Prairie View"	: "Prairie View A&M",
	"prairie-view-a&m-panthers"	: "Prairie View A&M",
	"Prairie View A&M"	: "Prairie View A&M",
	"Presbyterian Blue Hose"	: "Presbyterian",
	"presbyterian-blue-hose"	: "Presbyterian",
	"Presbyterian"	: "Presbyterian",
	"Princeton Tigers"	: "Princeton",
	"princeton-tigers"	: "Princeton",
	"Princeton"	: "Princeton",
	"Providence Friars"	: "Providence",
	"providence-friars"	: "Providence",
	"Providence"	: "Providence",
	"Purdue Boilermakers"	: "Purdue",
	"purdue-boilermakers"	: "Purdue",
	"Purdue"	: "Purdue",
	"Quinnipiac Bobcats"	: "Quinnipiac",
	"quinnipiac-bobcats"	: "Quinnipiac",
	"Quinnipiac"	: "Quinnipiac",
	"Radford Highlanders"	: "Radford",
	"radford-highlanders"	: "Radford",
	"Radford"	: "Radford",
	"Rhode Island Rams"	: "Rhode Island",
	"rhode-island-rams"	: "Rhode Island",
	"Rhode Island"	: "Rhode Island",
	"Rice Owls"	: "Rice",
	"rice-owls"	: "Rice",
	"Rice"	: "Rice",
	"Richmond Spiders"	: "Richmond",
	"richmond-spiders"	: "Richmond",
	"Richmond"	: "Richmond",
	"Rider Broncs"	: "Rider",
	"rider-broncs"	: "Rider",
	"Rider"	: "Rider",
	"R Morris"	: "Robert Morris",
	"Robert Morris Colonials"	: "Robert Morris",
	"robert-morris-colonials"	: "Robert Morris",
	"Robert Morris"	: "Robert Morris",
	"Rutgers Scarlet Knights"	: "Rutgers",
	"rutgers-scarlet-knights"	: "Rutgers",
	"Rutgers"	: "Rutgers",
	"S. Carolina St"	: "S. Carolina St.",
	"S Carolina St"	: "S. Carolina St.",
	"So Carolina St"	: "S. Carolina St.",
	"South Carolina St."	: "S. Carolina St.",
	"So Carolina St."	: "S. Carolina St.",
	"South Carolina State"	: "S. Carolina St.",
	"South Carolina State Bulldogs"	: "S. Carolina St.",
	"south-carolina-state-bulldogs"	: "S. Carolina St.",
	"S. Carolina St."	: "S. Carolina St.",
	"South Carolina Upstate"	: "S.Car. Upstate",
	"SC Upstate"	: "S.Car. Upstate",
	"South Carolina Upstate Spartans"	: "S.Car. Upstate",
	"USC Upstate"	: "S.Car. Upstate",
	"USC-Upstate"	: "S.Car. Upstate",
	"usc-upstate-spartans"	: "S.Car. Upstate",
	"S.Car. Upstate"	: "S.Car. Upstate",
	"Sacramento State"	: "Sacramento St.",
	"Sacramento St"	: "Sacramento St.",
	"Sacramento State Hornets"	: "Sacramento St.",
	"sacramento-state-hornets"	: "Sacramento St.",
	"Sacramento St."	: "Sacramento St.",
	"Sacred Heart Pioneers"	: "Sacred Heart",
	"sacred-heart-pioneers"	: "Sacred Heart",
	"Sacred Heart"	: "Sacred Heart",
	"Saint Louis Billikens"	: "Saint Louis",
	"St Louis"	: "Saint Louis",
	"saint-louis-billikens"	: "Saint Louis",
	"Saint Louis"	: "Saint Louis",
	"St. Louis"	: "Saint Louis",
	"Sam Houston"	: "Sam Houston St.",
	"Sam Houston St"	: "Sam Houston St.",
	"Sam Houston St. Bearkats"	: "Sam Houston St.",
	"sam-houston-state-bearkats"	: "Sam Houston St.",
	"Sam Houston St."	: "Sam Houston St.",
	"Samford Bulldogs"	: "Samford",
	"samford-bulldogs"	: "Samford",
	"Samford"	: "Samford",
	"San Diego Toreros"	: "San Diego",
	"san-diego-toreros"	: "San Diego",
	"San Diego"	: "San Diego",
	"San Diego St"	: "San Diego St.",
	"San Diego State"	: "San Diego St.",
	"San Diego St. Aztecs"	: "San Diego St.",
	"san-diego-state-aztecs"	: "San Diego St.",
	"San Diego St."	: "San Diego St.",
	"San Francisco Dons"	: "San Francisco",
	"san-francisco-dons"	: "San Francisco",
	"San Francisco"	: "San Francisco",
	"San Jose State"	: "San Jose St.",
	"San Jose St"	: "San Jose St.",
	"San Jose St. Spartans"	: "San Jose St.",
	"san-jose-state-spartans"	: "San Jose St.",
	"San Jose St."	: "San Jose St.",
	"Santa Clara Broncos"	: "Santa Clara",
	"santa-clara-broncos"	: "Santa Clara",
	"Santa Clara"	: "Santa Clara",
	"Savannah State"	: "Savannah St.",
	"Savannah St"	: "Savannah St.",
	"Savannah State Tigers"	: "Savannah St.",
	"savannah-state-tigers"	: "Savannah St.",
	"Savannah St."	: "Savannah St.",
	"Southeastern Louisiana"	: "SE Louisiana",
	"Southeastern Louisiana Lions"	: "SE Louisiana",
	"southeastern-louisiana-lions"	: "SE Louisiana",
	"SE Louisiana"	: "SE Louisiana",
	"Southeastern La."	: "SE Louisiana",
	"SE Missouri St"	: "SE Missouri St.",
	"Southeast Mo. St."	: "SE Missouri St.",
	"Southeast Missouri St."	: "SE Missouri St.",
	"SE Missouri St"	: "SE Missouri St.",
	"SE Missouri St. Redhawks"	: "SE Missouri St.",
	"southeast-missouri-state-redhawks"	: "SE Missouri St.",
	"SE Missouri St."	: "SE Missouri St.",
	"Seattle Redhawks"	: "Seattle",
	"Seattle U"	: "Seattle",
	"seattle-redhawks"	: "Seattle",
	"Seattle"	: "Seattle",
	"Seton Hall Pirates"	: "Seton Hall",
	"seton-hall-pirates"	: "Seton Hall",
	"Seton Hall"	: "Seton Hall",
	"Siena Saints"	: "Siena",
	"siena-saints"	: "Siena",
	"Siena"	: "Siena",
	"SIU - Edwardsville Cougars"	: "SIU Edwardsville",
	"SIU - Edwardsville"	: "SIU Edwardsville",
	"SIU-Edwardsville"	: "SIU Edwardsville",
	"Edwardsville"	: "SIU Edwardsville",
	"siu-edwardsville-cougars"	: "SIU Edwardsville",
	"SIU Edwardsville"	: "SIU Edwardsville",
	"Southern Methodist"	: "SMU",
	"Southern Methodist Mustangs"	: "SMU",
	"southern-methodist-mustangs"	: "SMU",
	"SMU"	: "SMU",
	"South Alabama Jaguars"	: "South Alabama",
	"South Ala."	: "South Alabama",
	"south-alabama-jaguars"	: "South Alabama",
	"South Alabama"	: "South Alabama",
	"South Carolina Gamecocks"	: "South Carolina",
	"south-carolina-gamecocks"	: "South Carolina",
	"South Carolina"	: "South Carolina",
	"South Dakota Coyotes"	: "South Dakota",
	"south-dakota-coyotes"	: "South Dakota",
	"South Dakota"	: "South Dakota",
	"S Dakota St"	: "South Dakota St.",
	"S Dakota St."	: "South Dakota St.",
	"South Dakota State"	: "South Dakota St.",
	"SD St."	: "South Dakota St.",
	"South Dakota St"	: "South Dakota St.",
	"SDSU"	: "South Dakota St.",
	"South Dakota State Jackrabbits"	: "South Dakota St.",
	"south-dakota-state-jackrabbits"	: "South Dakota St.",
	"South Dakota St."	: "South Dakota St.",
	"South Florida Bulls"	: "South Florida",
	"South Fla."	: "South Florida",
	"south-florida-bulls"	: "South Florida",
	"South Florida"	: "South Florida",
	"Southern Jaguars"	: "Southern",
	"Southern Univ"	: "Southern",
	"Southern U."	: "Southern",
	"southern-university-jaguars"	: "Southern",
	"Southern"	: "Southern",
	"So Illinois"	: "Southern Ill.",
	"Southern Illinois"	: "Southern Ill.",
	"S Illinois"	: "Southern Ill.",
	"Southern Illinois Salukis"	: "Southern Ill.",
	"southern-illinois-salukis"	: "Southern Ill.",
	"Southern Ill."	: "Southern Ill.",
	"So Mississippi"	: "Southern Miss",
	"Southern Miss."	: "Southern Miss",
	"Southern Mississippi"	: "Southern Miss",
	"Southern Mississippi Golden Eagles"	: "Southern Miss",
	"southern-miss-golden-eagles"	: "Southern Miss",
	"Southern Miss"	: "Southern Miss",
	"Southern Utah Thunderbirds"	: "Southern Utah",
	"southern-utah-thunderbirds"	: "Southern Utah",
	"Southern Utah"	: "Southern Utah",
	"St. Bonaventure Bonnies"	: "St. Bonaventure",
	"St Bonaventure"	: "St. Bonaventure",
	"st.-bonaventure-bonnies"	: "St. Bonaventure",
	"St. Bonaventure"	: "St. Bonaventure",
	"St Francis NY"	: "St. Francis (NY)",
	"St. Francis Brooklyn"	: "St. Francis (NY)",
	"St Francis (NY)"	: "St. Francis (NY)",
	"St. Francis NY"	: "St. Francis (NY)",
	"St. Francis-NY Terriers"	: "St. Francis (NY)",
	"st.-francis-(ny-terriers)"	: "St. Francis (NY)",
	"St. Francis (NY)"	: "St. Francis (NY)",
	"St Francis PA"	: "St. Francis (PA)",
	"St Francis (PA)"	: "St. Francis (PA)",
	"Saint Francis (PA)"	: "St. Francis (PA)",
	"St. Francis (PA) Red Flash"	: "St. Francis (PA)",
	"St. Francis PA"	: "St. Francis (PA)",
	"st.-francis-(pa-red-flash)"	: "St. Francis (PA)",
	"St. Francis (PA)"	: "St. Francis (PA)",
	"St. John's Red Storm"	: "St. John's",
	"St John's"	: "St. John's",
	"St. John's (NY)"	: "St. John's",
	"St. Johns"	: "St. John's",
	"st.-john's-red-storm"	: "St. John's",
	"St. John's"	: "St. John's",
	"St. Joseph's Hawks"	: "St. Joseph's",
	"St Joseph's PA"	: "St. Joseph's",
	"Saint Joseph's"	: "St. Joseph's",
	"St. Josephs"	: "St. Joseph's",
	"saint-joseph's-hawks"	: "St. Joseph's",
	"St. Joseph's"	: "St. Joseph's",
	"Saint Marys CA"	: "St. Mary's",
	"St. Mary's (CA)"	: "St. Mary's",
	"St. Mary's Gaels"	: "St. Mary's",
	"Saint Mary's"	: "St. Mary's",
	"St Mary's CA"	: "St. Mary's",
	"saint-mary's-gaels"	: "St. Mary's",
	"St. Mary's"	: "St. Mary's",
	"St Peter's"	: "St. Peter's",
	"Saint Peter's"	: "St. Peter's",
	"St. Peter's Peacocks"	: "St. Peter's",
	"st.-peter's-peacocks"	: "St. Peter's",
	"St. Peter's"	: "St. Peter's",
	"Stanford Cardinal"	: "Stanford",
	"stanford-cardinal"	: "Stanford",
	"Stanford"	: "Stanford",
	"Stephen Austin"	: "Stephen F. Austin",
	"Stephen F. Austin Lumberjacks"	: "Stephen F. Austin",
	"SF Austin"	: "Stephen F. Austin",
	"stephen-f.-austin-lumberjacks"	: "Stephen F. Austin",
	"Stephen F. Austin"	: "Stephen F. Austin",
	"Stetson Hatters"	: "Stetson",
	"stetson-hatters"	: "Stetson",
	"Stetson"	: "Stetson",
	"Stony Brook Seawolves"	: "Stony Brook",
	"stony-brook-seawolves"	: "Stony Brook",
	"Stony Brook"	: "Stony Brook",
	"Syracuse Orange"	: "Syracuse",
	"syracuse-orange"	: "Syracuse",
	"Syracuse"	: "Syracuse",
	"TAM C. Christi"	: "TAMU Corpus Christi",
	"Texas A&M Corpus Chris"	: "TAMU Corpus Christi",
	"A&M-Corpus Christi"	: "TAMU Corpus Christi",
	"Texas A&M CC"	: "TAMU Corpus Christi",
	"Texas A&M CC Islanders"	: "TAMU Corpus Christi",
	"Texas A&M Corpus"	: "TAMU Corpus Christi",
	"Texas A&M-CC"	: "TAMU Corpus Christi",
	"texas-a&m-cc-islanders"	: "TAMU Corpus Christi",
	"TAMU Corpus Christi"	: "TAMU Corpus Christi",
	"Texas Christian"	: "TCU",
	"Texas Christian Horned Frogs"	: "TCU",
	"Texas Christian Horned Frogs"	: "TCU",
	"tcu-horned-frogs"	: "TCU",
	"TCU"	: "TCU",
	"Temple Owls"	: "Temple",
	"temple-owls"	: "Temple",
	"Temple"	: "Temple",
	"TN Martin"	: "Tenn-Martin",
	"Tennessee Martin"	: "Tenn-Martin",
	"Tenn.-Martin"	: "Tenn-Martin",
	"UT Martin"	: "Tenn-Martin",
	"Tenn Martin"	: "Tenn-Martin",
	"Tenn-Martin Skyhawks"	: "Tenn-Martin",
	"tennessee-martin-skyhawks"	: "Tenn-Martin",
	"Tenn-Martin"	: "Tenn-Martin",
	"Tennessee Volunteers"	: "Tennessee",
	"tennessee-volunteers"	: "Tennessee",
	"Tennessee"	: "Tennessee",
	"Tennessee St"	: "Tennessee St.",
	"Tennessee St. Tigers"	: "Tennessee St.",
	"tennessee-state-tigers"	: "Tennessee St.",
	"Tennessee St."	: "Tennessee St.",
	"Tennessee Tech Golden Eagles"	: "Tennessee Tech",
	"tennessee-tech-golden-eagles"	: "Tennessee Tech",
	"Tennessee Tech"	: "Tennessee Tech",
	"Texas Longhorns"	: "Texas",
	"texas-longhorns"	: "Texas",
	"Texas"	: "Texas",
	"Texas A&M Aggies"	: "Texas A&M",
	"Texas Wesleyan Rams"	: "Texas A&M",
	"texas-a&m-aggies"	: "Texas A&M",
	"Texas A&M"	: "Texas A&M",
	"TX Southern"	: "Texas Southern",
	"Texas Southern Tigers"	: "Texas Southern",
	"texas-southern-tigers"	: "Texas Southern",
	"Texas Southern"	: "Texas Southern",
	"Texas State"	: "Texas St.",
	"Texas St"	: "Texas St.",
	"Texas State Bobcats"	: "Texas St.",
	"texas-state-bobcats"	: "Texas St.",
	"Texas St."	: "Texas St.",
	"Texas Tech Red Raiders"	: "Texas Tech",
	"texas-tech-red-raiders"	: "Texas Tech",
	"Texas Tech"	: "Texas Tech",
	"Toledo Rockets"	: "Toledo",
	"toledo-rockets"	: "Toledo",
	"Toledo"	: "Toledo",
	"Towson Tigers"	: "Towson",
	"towson-tigers"	: "Towson",
	"Towson"	: "Towson",
	"Troy Trojans"	: "Troy",
	"troy-trojans"	: "Troy",
	"Troy"	: "Troy",
	"Tulane Green Wave"	: "Tulane",
	"tulane-green-wave"	: "Tulane",
	"Tulane"	: "Tulane",
	"Tulsa Golden Hurricane"	: "Tulsa",
	"tulsa-golden-hurricane"	: "Tulsa",
	"Tulsa"	: "Tulsa",
	"UT Arlington"	: "TX Arlington",
	"TX-Arlington"	: "TX Arlington",
	"Texas-Arlington"	: "TX Arlington",
	"Texas Arlington"	: "TX Arlington",
	"Texas-Arlington Mavericks"	: "TX Arlington",
	"texas-arlington-mavericks"	: "TX Arlington",
	"TX Arlington"	: "TX Arlington",
	"TX-Pan American"	: "TX Pan American",
	"Texas-Pan American Broncs"	: "TX Pan American",
	"Tex.-Pan American"	: "TX Pan American",
	"Texas-Pan American"	: "TX Pan American",
	"Texas Pan American"	: "TX Pan American",
	"texas-pan-american-broncs"	: "TX Pan American",
	"TX Pan American"	: "TX Pan American",
	"UAB Blazers"	: "UAB",
	"uab-blazers"	: "UAB",
	"UAB"	: "UAB",
	"UC Davis Aggies"	: "UC Davis",
	"uc-davis-aggies"	: "UC Davis",
	"UC Davis"	: "UC Davis",
	"Cal Irvine"	: "UC Irvine",
	"UC Irvine Anteaters"	: "UC Irvine",
	"uc-irvine-anteaters"	: "UC Irvine",
	"UC Irvine"	: "UC Irvine",
	"Cal Riverside"	: "UC Riverside",
	"UC Riverside Highlanders"	: "UC Riverside",
	"uc-riverside-highlanders"	: "UC Riverside",
	"UC Riverside"	: "UC Riverside",
	"Central Florida Golden Knights"	: "UCF",
	"Central Florida"	: "UCF",
	"ucf-knights"	: "UCF",
	"UCF"	: "UCF",
	"UCLA Bruins"	: "UCLA",
	"ucla-bruins"	: "UCLA",
	"UCLA"	: "UCLA",
	"Cal Santa Barb"	: "UCSB",
	"Cal Santa Barb."	: "UCSB",
	"UC Santa Barbara"	: "UCSB",
	"Santa Barbara"	: "UCSB",
	"UC Santa Barbara Gauchos"	: "UCSB",
	"uc-santa-barbara-gauchos"	: "UCSB",
	"UCSB"	: "UCSB",
	"MD Baltimore Cty"	: "UMBC",
	"MD Baltimore Co"	: "UMBC",
	"MD Baltimore Cty Retrievers"	: "UMBC",
	"umbc-retrievers"	: "UMBC",
	"UMBC"	: "UMBC",
	"UNLV Runnin' Rebels"	: "UNLV",
	"unlv-rebels"	: "UNLV",
	"UNLV"	: "UNLV",
	"Southern California"	: "USC",
	"Southern California Trojans"	: "USC",
	"usc-trojans"	: "USC",
	"USC"	: "USC",
	"Utah U"	: "Utah",
	"Utah Utes"	: "Utah",
	"utah-utes"	: "Utah",
	"Utah"	: "Utah",
	"Utah State"	: "Utah St.",
	"Utah St"	: "Utah St.",
	"Utah St. Aggies"	: "Utah St.",
	"utah-state-aggies"	: "Utah St.",
	"Utah St."	: "Utah St.",
	"Utah Valley Wolverines"	: "Utah Valley",
	"utah-valley-wolverines"	: "Utah Valley",
	"Utah Valley"	: "Utah Valley",
	"Texas-El Paso"	: "UTEP",
	"Texas-El Paso Miners"	: "UTEP",
	"utep-miners"	: "UTEP",
	"UTEP"	: "UTEP",
	"UT San Antonio"	: "UTSA",
	"Tex San Antonio"	: "UTSA",
	"Texas-San Antonio"	: "UTSA",
	"Texas-San Antonio Roadrunners"	: "UTSA",
	"utsa-roadrunners"	: "UTSA",
	"UTSA"	: "UTSA",
	"Valparaiso Crusaders"	: "Valparaiso",
	"valparaiso-crusaders"	: "Valparaiso",
	"Valparaiso"	: "Valparaiso",
	"Vanderbilt Commodores"	: "Vanderbilt",
	"vanderbilt-commodores"	: "Vanderbilt",
	"Vanderbilt"	: "Vanderbilt",
	"VCU Rams"	: "VCU",
	"Virginia Commonwealth"	: "VCU",
	"VA Commonwealth"	: "VCU",
	"Va Commonwealth"	: "VCU",
	"virginia-commonwealth-rams"	: "VCU",
	"VCU"	: "VCU",
	"Vermont Catamounts"	: "Vermont",
	"vermont-catamounts"	: "Vermont",
	"Vermont"	: "Vermont",
	"Villanova Wildcats"	: "Villanova",
	"villanova-wildcats"	: "Villanova",
	"Villanova"	: "Villanova",
	"Virginia Cavaliers"	: "Virginia",
	"virginia-cavaliers"	: "Virginia",
	"Virginia"	: "Virginia",
	"VMI Keydets"	: "Virginia Military",
	"VMI"	: "Virginia Military",
	"virginia-military-keydets"	: "Virginia Military",
	"Virginia Military"	: "Virginia Military",
	"Virginia Tech Hokies"	: "Virginia Tech",
	"virginia-tech-hokies"	: "Virginia Tech",
	"Virginia Tech"	: "Virginia Tech",
	"W Michigan"	: "W. Michigan",
	"Western Michigan Broncos"	: "W. Michigan",
	"Western Michigan"	: "W. Michigan",
	"Western Mich."	: "W. Michigan",
	"western-michigan-broncos"	: "W. Michigan",
	"W. Michigan"	: "W. Michigan",
	"Wagner Seahawks"	: "Wagner",
	"wagner-seahawks"	: "Wagner",
	"Wagner"	: "Wagner",
	"Wake Forest Demon Deacons"	: "Wake Forest",
	"wake-forest-demon-deacons"	: "Wake Forest",
	"Wake Forest"	: "Wake Forest",
	"Washington Huskies"	: "Washington",
	"Washington U"	: "Washington",
	"washington-huskies"	: "Washington",
	"Washington"	: "Washington",
	"Washington St"	: "Washington St.",
	"Washington St. Cougars"	: "Washington St.",
	"washington-state-cougars"	: "Washington St.",
	"Washington St."	: "Washington St.",
	"Weber State"	: "Weber St.",
	"Weber St"	: "Weber St.",
	"Weber St. Wildcats"	: "Weber St.",
	"weber-state-wildcats"	: "Weber St.",
	"Weber St."	: "Weber St.",
	"West Virginia Mountaineers"	: "West Virginia",
	"west-virginia-mountaineers"	: "West Virginia",
	"West Virginia"	: "West Virginia",
	"Western Kentucky Hilltoppers"	: "West. Kentucky",
	"Western Ky."	: "West. Kentucky",
	"Western Kentucky"	: "West. Kentucky",
	"W Kentucky"	: "West. Kentucky",
	"western-kentucky-hilltoppers"	: "West. Kentucky",
	"West. Kentucky"	: "West. Kentucky",
	"Western Carolina Catamounts"	: "Western Carolina",
	"Western Caro."	: "Western Carolina",
	"W Carolina"	: "Western Carolina",
	"western-carolina-catamounts"	: "Western Carolina",
	"Western Carolina"	: "Western Carolina",
	"Western Illinois Leathernecks"	: "Western Ill.",
	"Western Illinois"	: "Western Ill.",
	"W Illinois"	: "Western Ill.",
	"western-illinois-leathernecks"	: "Western Ill.",
	"Western Ill."	: "Western Ill.",
	"Wichita St"	: "Wichita St.",
	"Wichita St. Shockers"	: "Wichita St.",
	"Wichita State"	: "Wichita St.",
	"wichita-state-shockers"	: "Wichita St.",
	"Wichita St."	: "Wichita St.",
	"William & Mary Tribe"	: "William & Mary",
	"william-&-mary-tribe"	: "William & Mary",
	"William & Mary"	: "William & Mary",
	"Winston-Salem" : "Winston Salem",
	"Winston Salem" : "Winston Salem",
	"Winston Salem St." : "Winston Salem",
	"Winthrop Eagles"	: "Winthrop",
	"winthrop-eagles"	: "Winthrop",
	"Winthrop"	: "Winthrop",
	"Wis.-Green Bay"	: "Wis. Green Bay",
	"Wis.-Green Bay Phoenix"	: "Wis. Green Bay",
	"WI Green Bay"	: "Wis. Green Bay",
	"Wisc Green Bay"	: "Wis. Green Bay",
	"Green Bay"	: "Wis. Green Bay",
	"green-bay-phoenix"	: "Wis. Green Bay",
	"Wis. Green Bay"	: "Wis. Green Bay",
	"WI Milwaukee"	: "Wis. Milwaukee",
	"Wis.-Milwaukee"	: "Wis. Milwaukee",
	"Wis.-Milwaukee Panthers"	: "Wis. Milwaukee",
	"Wisc Milwaukee"	: "Wis. Milwaukee",
	"Milwaukee"	: "Wis. Milwaukee",
	"milwaukee-panthers"	: "Wis. Milwaukee",
	"Wis. Milwaukee"	: "Wis. Milwaukee",
	"Wisconsin Badgers"	: "Wisconsin",
	"wisconsin-badgers"	: "Wisconsin",
	"Wisconsin"	: "Wisconsin",
	"Wofford Terriers"	: "Wofford",
	"wofford-terriers"	: "Wofford",
	"Wofford"	: "Wofford",
	"Wright State"	: "Wright St.",
	"Wright St"	: "Wright St.",
	"Wright St. Raiders"	: "Wright St.",
	"wright-state-raiders"	: "Wright St.",
	"Wright St."	: "Wright St.",
	"Wyoming Cowboys"	: "Wyoming",
	"wyoming-cowboys"	: "Wyoming",
	"Wyoming"	: "Wyoming",
	"Xavier Musketeers"	: "Xavier",
	"xavier-musketeers"	: "Xavier",
	"Xavier"	: "Xavier",
	"Yale Bulldogs"	: "Yale",
	"yale-bulldogs"	: "Yale",
	"Yale"	: "Yale",
	"Youngstown St"	: "Youngstown St.",
	"Youngstown St. Penguins"	: "Youngstown St.",
	"youngstown-state-penguins"	: "Youngstown St.",
	"Youngstown St."	: "Youngstown St.",
	"Albany-NY" : "Albany",
	"American University" : "American",
	"Appalachian State" : "Appalachian St.",
	"Ark.-Little Rock" : "AR Little Rock",
	"Binghamton-NY" : "Binghamton",
	"Birmingham-Southern" : "Birmingham Sou.",
	"Cal Poly-SLO" : "Cal Poly",
	"Cent. Connecticut St." : "Central Conn. St.",
	"Cent. Connecticut State" : "Central Conn. St.",
	"Central Connecticut St." : "Central Conn. St.",
	"Central Florida(UCF)" : "UCF",
	"East Tennessee State" : "E. Tennessee St.",
	"Fla. International" : "Florida Intl.",
	"Fort Wayne(IPFW)" : "IPFW",
	"Hawai'i" : "Hawaii",
	"Jacksonville State" : "Jacksonville St.",
	"Kansas City(UMKC)" : "Mo. Kansas City",
	"Long Island U." : "Long Island",
	"Long Island University" : "Long Island",
	"Md.-Eastern Shore" : "MD Eastern Shore",
	"Md.-Eastern Shore(UMES)" : "MD Eastern Shore",
	"Miami-Ohio" : "Miami (OH)",
	"Mississippi State" : "Mississippi St.",
	"MVSU (Miss. Valley St.)" : "Miss. Valley St.",
	"MVSU(Miss. Valley St.)" : "Miss. Valley St.",
	"NJIT(New Jersey Tech)" : "N.J.I.T.",
	"No. Carolina St." : "N.C. State",
	"North Florida(UNF)" : "North Florida",
	"Northwestern State" : "Northwestern St.",
	"Oakland-Mich." : "Oakland",
	"Ohio U." : "Ohio",
	"Ohio University" : "Ohio",
	"Omaha(Neb.-Omaha)" : "Nebraska Omaha",
	"Presbyterian College" : "Presbyterian",
	"Saint Francis-Pa." : "St. Francis (PA)",
	"Saint Joseph's-Pa." : "St. Joseph's",
	"Saint Mary's-Cal." : "St. Mary's",
	"Sam Houston State" : "Sam Houston St.",
	"SC State" : "S. Carolina St.",
	"SE Missouri State" : "SE Missouri St.",
	"SE Missouri State(SEMO)" : "SE Missouri St.",
	"So. Carolina St." : "S. Carolina St.",
	"So. Carolina State" : "S. Carolina St.",
	"Southern Cal" : "USC",
	"Southern University" : "Southern",
	"St. Francis-NY" : "St. Francis (NY)",
	"St. Francis-Pa." : "St. Francis (PA)",
	"Stony Brook-NY" : "Stony Brook",
	"Tennessee State" : "Tennessee St.",
	"Tennessee-Martin" : "Tenn-Martin",
	"Texas A&M CorpusChristi" : "TAMU Corpus Christi",
	"Texas A&M-CorpusChristi" : "TAMU Corpus Christi",
	"Texas-San Antonio(UTSA)" : "UTSA",
	"UCF (Central Florida)" : "UCF",
	"UCF(Central Florida)" : "UCF",
	"UMES(Md.-Eastern Shore)" : "MD Eastern Shore",
	"Utah Valley State" : "Utah Valley",
	"Va. Commonwealth" : "VCU",
	"VCU(Va. Commonwealth)" : "VCU",
	"Washington State" : "Washington St.",
	"Winston-Salem State" : "Winston Salem",
	"Xavier-Ohio" : "Xavier",
	"Youngstown State" : "Youngstown St.",
	"Albany, N.Y." : "Albany",
	"Buter" : "Butler",
	"C. Connecticut State" : "Central Conn. St.",
	"C. Michigan" : "Cent. Michigan",
	"Cal State Fullerton" : "CSU Fullerton",
	"Cal State Northridge" : "CSU Northridge",
	"Cincnnati" : "Cincinnati",
	"Ill-Chicago" : "Ill. Chicago",
	"LIU" : "Long Island",
	"Loyola (Md.)" : "Loyola (MD)",
	"Maryland-Baltimore County" : "Maryland",
	"Miami" : "Miami (FL)",
	"Miami (Fla.)" : "Miami (FL)",
	"Miami (Ohio)" : "Miami (OH)",
	"Monmouth, N.J." : "Monmouth",
	"Mount St. Mary's, Md." : "Mount St. Mary's",
	"MVSU" : "Miss. Valley St.",
	"N. Carolina St." : "N.C. State",
	"N. Iowa" : "Northern Iowa",
	"Oakland, Mich." : "Oakland",
	"S. Illinois" : "Southern Ill.",
	"Saint Mary's (Calif.)" : "St. Mary's",
	"Saint Mary's, Calif." : "St. Mary's",
	"Troy St." : "Troy",
	"TX-San Antonio" : "UTSA",
	"W. Kentucky" : "West. Kentucky",
	"WI-Milwaulee" : "Wisconsin",
	"Wisconsin-Milwaukee" : "Wisconsin",
	"Bryant University" : "Bryant",
	"Cal State Bakersfield" : "CSU Bakersfield",
	"California Davis" : "UC Davis",
	"California Irvine" : "UC Irvine",
	"California Riverside" : "UC Riverside",
	"Central Connecticut State" : "Central Conn. St.",
	"E. Tennessee State" : "E. Tennessee St.",
	"LIU-Brooklyn" : "Long Island",
	"Maryland-Eastern Shore" : "MD Eastern Shore",
	"NC-Asheville" : "N.C. Asheville",
	"New Jersey Tech" : "N.J.I.T.",
	"Southeast Missouri State" : "SE Missouri St.",
	"St. Francis (N.Y.)" : "St. Francis (NY)",
	"St. Francis (Pa.)" : "St. Francis (PA)",
	"Texas A&M-Corpus Christi" : "TAMU Corpus Christi",
}

KAGGLE_MAP = {
	"501"	: "Abilene Chr",
	"502"	: "Air Force",
	"503"	: "Akron",
	"504"	: "Alabama",
	"505"	: "Alabama A&M",
	"506"	: "Alabama St",
	"507"	: "Albany NY",
	"508"	: "Alcorn St",
	"509"	: "American Univ",
	"510"	: "Appalachian St",
	"511"	: "Arizona",
	"512"	: "Arizona St",
	"513"	: "Ark Little Rock",
	"514"	: "Ark Pine Bluff",
	"515"	: "Arkansas",
	"516"	: "Arkansas St",
	"517"	: "Army",
	"518"	: "Auburn",
	"519"	: "Austin Peay",
	"520"	: "Ball St",
	"521"	: "Baylor",
	"522"	: "Belmont",
	"523"	: "Bethune-Cookman",
	"524"	: "Binghamton",
	"525"	: "Birmingham So",
	"526"	: "Boise St",
	"527"	: "Boston College",
	"528"	: "Boston Univ",
	"529"	: "Bowling Green",
	"530"	: "Bradley",
	"531"	: "Brown",
	"532"	: "Bryant",
	"533"	: "Bucknell",
	"534"	: "Buffalo",
	"535"	: "Butler",
	"536"	: "BYU",
	"537"	: "C Michigan",
	"538"	: "Cal Poly SLO",
	"539"	: "California",
	"540"	: "Campbell",
	"541"	: "Canisius",
	"542"	: "Cent Arkansas",
	"543"	: "Centenary",
	"544"	: "Central Conn",
	"545"	: "Charleston So",
	"546"	: "Charlotte",
	"547"	: "Chattanooga",
	"548"	: "Chicago St",
	"549"	: "Cincinnati",
	"550"	: "Citadel",
	"551"	: "Clemson",
	"552"	: "Cleveland St",
	"553"	: "Coastal Car",
	"554"	: "Col Charleston",
	"555"	: "Colgate",
	"556"	: "Colorado",
	"557"	: "Colorado St",
	"558"	: "Columbia",
	"559"	: "Connecticut",
	"560"	: "Coppin St",
	"561"	: "Cornell",
	"562"	: "Creighton",
	"563"	: "CS Bakersfield",
	"564"	: "CS Fullerton",
	"565"	: "CS Northridge",
	"566"	: "CS Sacramento",
	"567"	: "Dartmouth",
	"568"	: "Davidson",
	"569"	: "Dayton",
	"570"	: "Delaware",
	"571"	: "Delaware St",
	"572"	: "Denver",
	"573"	: "DePaul",
	"574"	: "Detroit",
	"575"	: "Drake",
	"576"	: "Drexel",
	"577"	: "Duke",
	"578"	: "Duquesne",
	"579"	: "E Illinois",
	"580"	: "E Kentucky",
	"581"	: "E Michigan",
	"582"	: "E Washington",
	"583"	: "East Carolina",
	"584"	: "Edwardsville",
	"585"	: "Elon",
	"586"	: "ETSU",
	"587"	: "Evansville",
	"588"	: "F Dickinson",
	"589"	: "Fairfield",
	"590"	: "FL Atlantic",
	"591"	: "FL Gulf Coast",
	"592"	: "Florida",
	"593"	: "Florida A&M",
	"594"	: "Florida Intl",
	"595"	: "Florida St",
	"596"	: "Fordham",
	"597"	: "Fresno St",
	"598"	: "Furman",
	"599"	: "G Washington",
	"600"	: "Ga Southern",
	"601"	: "Gardner Webb",
	"602"	: "George Mason",
	"603"	: "Georgetown",
	"604"	: "Georgia",
	"605"	: "Georgia St",
	"606"	: "Georgia Tech",
	"607"	: "Gonzaga",
	"608"	: "Grambling",
	"609"	: "Grand Canyon",
	"610"	: "Hampton",
	"611"	: "Hartford",
	"612"	: "Harvard",
	"613"	: "Hawaii",
	"614"	: "High Point",
	"615"	: "Hofstra",
	"616"	: "Holy Cross",
	"617"	: "Houston",
	"618"	: "Houston Bap",
	"619"	: "Howard",
	"620"	: "Idaho",
	"621"	: "Idaho St",
	"622"	: "IL Chicago",
	"623"	: "Illinois",
	"624"	: "Illinois St",
	"625"	: "Indiana",
	"626"	: "Indiana St",
	"627"	: "Iona",
	"628"	: "Iowa",
	"629"	: "Iowa St",
	"630"	: "IPFW",
	"631"	: "IUPUI",
	"632"	: "Jackson St",
	"633"	: "Jacksonville",
	"634"	: "Jacksonville St",
	"635"	: "James Madison",
	"636"	: "Kansas",
	"637"	: "Kansas St",
	"638"	: "Kennesaw",
	"639"	: "Kent",
	"640"	: "Kentucky",
	"641"	: "La Salle",
	"642"	: "Lafayette",
	"643"	: "Lamar",
	"644"	: "Lehigh",
	"645"	: "Liberty",
	"646"	: "Lipscomb",
	"647"	: "Long Beach St",
	"648"	: "Long Island",
	"649"	: "Longwood",
	"650"	: "Louisiana Tech",
	"651"	: "Louisville",
	"652"	: "Loy Marymount",
	"653"	: "Loyola MD",
	"654"	: "Loyola-Chicago",
	"655"	: "LSU",
	"656"	: "MA Lowell",
	"657"	: "Maine",
	"658"	: "Manhattan",
	"659"	: "Marist",
	"660"	: "Marquette",
	"661"	: "Marshall",
	"662"	: "Maryland",
	"663"	: "Massachusetts",
	"664"	: "McNeese St",
	"665"	: "MD E Shore",
	"666"	: "Memphis",
	"667"	: "Mercer",
	"668"	: "Miami FL",
	"669"	: "Miami OH",
	"670"	: "Michigan",
	"671"	: "Michigan St",
	"672"	: "Middle Tenn St",
	"673"	: "Minnesota",
	"674"	: "Mississippi",
	"675"	: "Mississippi St",
	"676"	: "Missouri",
	"677"	: "Missouri KC",
	"678"	: "Missouri St",
	"679"	: "Monmouth NJ",
	"680"	: "Montana",
	"681"	: "Montana St",
	"682"	: "Morehead St",
	"683"	: "Morgan St",
	"684"	: "Morris Brown",
	"685"	: "MS Valley St",
	"686"	: "Mt St Mary's",
	"687"	: "Murray St",
	"688"	: "N Colorado",
	"689"	: "N Dakota St",
	"690"	: "N Illinois",
	"691"	: "N Kentucky",
	"692"	: "Navy",
	"693"	: "NC A&T",
	"694"	: "NC Central",
	"695"	: "NC State",
	"696"	: "NE Illinois",
	"697"	: "NE Omaha",
	"698"	: "Nebraska",
	"699"	: "Nevada",
	"700"	: "New Hampshire",
	"701"	: "New Mexico",
	"702"	: "New Mexico St",
	"703"	: "New Orleans",
	"704"	: "Niagara",
	"705"	: "Nicholls St",
	"706"	: "NJIT",
	"707"	: "Norfolk St",
	"708"	: "North Carolina",
	"709"	: "North Dakota",
	"710"	: "North Florida",
	"711"	: "North Texas",
	"712"	: "Northeastern",
	"713"	: "Northern Arizona",
	"714"	: "Northern Iowa",
	"715"	: "Northwestern",
	"716"	: "Northwestern LA",
	"717"	: "Notre Dame",
	"718"	: "Oakland",
	"719"	: "Ohio",
	"720"	: "Ohio St",
	"721"	: "Oklahoma",
	"722"	: "Oklahoma St",
	"723"	: "Old Dominion",
	"724"	: "Oral Roberts",
	"725"	: "Oregon",
	"726"	: "Oregon St",
	"727"	: "Pacific",
	"728"	: "Penn",
	"729"	: "Penn St",
	"730"	: "Pepperdine",
	"731"	: "Pittsburgh",
	"732"	: "Portland",
	"733"	: "Portland St",
	"734"	: "Prairie View",
	"735"	: "Presbyterian",
	"736"	: "Princeton",
	"737"	: "Providence",
	"738"	: "Purdue",
	"739"	: "Quinnipiac",
	"740"	: "Radford",
	"741"	: "Rhode Island",
	"742"	: "Rice",
	"743"	: "Richmond",
	"744"	: "Rider",
	"745"	: "Robert Morris",
	"746"	: "Rutgers",
	"747"	: "S Carolina St",
	"748"	: "S Dakota St",
	"749"	: "S Illinois",
	"750"	: "Sacred Heart",
	"751"	: "Sam Houston St",
	"752"	: "Samford",
	"753"	: "San Diego",
	"754"	: "San Diego St",
	"755"	: "San Francisco",
	"756"	: "San Jose St",
	"757"	: "Santa Barbara",
	"758"	: "Santa Clara",
	"759"	: "Savannah St",
	"760"	: "SC Upstate",
	"761"	: "SE Louisiana",
	"762"	: "SE Missouri St",
	"763"	: "Seattle",
	"764"	: "Seton Hall",
	"765"	: "SF Austin",
	"766"	: "Siena",
	"767"	: "SMU",
	"768"	: "South Alabama",
	"769"	: "South Carolina",
	"770"	: "South Dakota",
	"771"	: "South Florida",
	"772"	: "Southern Miss",
	"773"	: "Southern Univ",
	"774"	: "Southern Utah",
	"775"	: "St Bonaventure",
	"776"	: "St Francis NY",
	"777"	: "St Francis PA",
	"778"	: "St John's",
	"779"	: "St Joseph's PA",
	"780"	: "St Louis",
	"781"	: "St Mary's CA",
	"782"	: "St Peter's",
	"783"	: "Stanford",
	"784"	: "Stetson",
	"785"	: "Stony Brook",
	"786"	: "Syracuse",
	"787"	: "TAM C. Christi",
	"788"	: "TCU",
	"789"	: "Temple",
	"790"	: "Tennessee",
	"791"	: "Tennessee St",
	"792"	: "Tennessee Tech",
	"793"	: "Texas",
	"794"	: "Texas A&M",
	"795"	: "Texas St",
	"796"	: "Texas Tech",
	"797"	: "TN Martin",
	"798"	: "Toledo",
	"799"	: "Towson",
	"800"	: "Troy",
	"801"	: "Tulane",
	"802"	: "Tulsa",
	"803"	: "TX Pan American",
	"804"	: "TX Southern",
	"805"	: "UAB",
	"806"	: "UC Davis",
	"807"	: "UC Irvine",
	"808"	: "UC Riverside",
	"809"	: "UCF",
	"810"	: "UCLA",
	"811"	: "ULL",
	"812"	: "ULM",
	"813"	: "UMBC",
	"814"	: "UNC Asheville",
	"815"	: "UNC Greensboro",
	"816"	: "UNC Wilmington",
	"817"	: "UNLV",
	"818"	: "USC",
	"819"	: "UT Arlington",
	"820"	: "UT San Antonio",
	"821"	: "Utah",
	"822"	: "Utah St",
	"823"	: "Utah Valley",
	"824"	: "UTEP",
	"825"	: "VA Commonwealth",
	"826"	: "Valparaiso",
	"827"	: "Vanderbilt",
	"828"	: "Vermont",
	"829"	: "Villanova",
	"830"	: "Virginia",
	"831"	: "Virginia Tech",
	"832"	: "VMI",
	"833"	: "W Carolina",
	"834"	: "W Illinois",
	"835"	: "W Kentucky",
	"836"	: "W Michigan",
	"837"	: "W Salem St",
	"838"	: "Wagner",
	"839"	: "Wake Forest",
	"840"	: "Washington",
	"841"	: "Washington St",
	"842"	: "Weber St",
	"843"	: "West Virginia",
	"844"	: "WI Green Bay",
	"845"	: "WI Milwaukee",
	"846"	: "Wichita St",
	"847"	: "William & Mary",
	"848"	: "Winthrop",
	"849"	: "Wisconsin",
	"850"	: "Wofford",
	"851"	: "Wright St",
	"852"	: "Wyoming",
	"853"	: "Xavier",
	"854"	: "Yale",
	"855"	: "Youngstown St",
	"856"	: "Incarnate Word"
}

YEAR_MAP = {
	'O' : 2010,
	'P' : 2011,
	'Q' : 2012,
	'R' : 2013,
	'S' : 2014,
}

SEED_FILENAME = '../data/tourney_seeds.csv'
SLOT_FILENAME = '../data/tourney_slots.csv'

seed_map = {
	2010 : {},
	2011 : {},
	2012 : {},
	2013 : {},
	2014 : {},
}

slot_map = {
	2010 : [],
	2011 : [],
	2012 : [],
	2013 : [],
	2014 : [],
}

score_dict = {
	2010 : [],
	2011 : [],
	2012 : [],
	2013 : [],
	2014 : [],
}

correct_dict = {
	2010 : [],
	2011 : [],
	2012 : [],
	2013 : [],
	2014 : [],
}

#f,seed,team
reader = csv.DictReader(open(SEED_FILENAME, 'rU'), skipinitialspace=True)
for row in reader:
	season = row['f']
	if season not in YEAR_MAP:
		continue

	seed = row['seed']
	team = row['team']

	year = YEAR_MAP.get(season)
	team_name = NAME_MAP.get(KAGGLE_MAP.get(team))

	seed_map[year][seed] = team_name

#season,slot,strongseed,weakseed
reader = csv.DictReader(open(SLOT_FILENAME, 'rU'), skipinitialspace=True)
for row in reader:
	season = row['season']
	if season not in YEAR_MAP:
		continue

	slot = row['slot']
	strongseed = row['strongseed']
	weakseed = row['weakseed']

	year = YEAR_MAP.get(season)

	slot_map[year].append((slot, strongseed, weakseed))


years = xrange(2010, 2014 + 1)
for year in years:
	print year
	games = Game.games_after_with_filter(25, rank_systems=("RPI", "SAG", "POM", "MOR",), exclude_year=year)

	print len(games)

	tr_data = np.array([g.selected_features() for g in games], dtype=np.float)
	tr_labels = np.array([g.upset() for g in games])
	tr_points_diff = np.array([g.points_diff() for g in games], dtype=np.float)

	tr_non_nan_indices = ~np.isnan(tr_data).any(axis=1)
	tr_data = tr_data[tr_non_nan_indices]
	tr_labels = tr_labels[tr_non_nan_indices]
	tr_points_diff = tr_points_diff[tr_non_nan_indices]

	mean = np.mean(tr_data, axis=0)
	std = np.std(tr_data, axis=0)
	tr_data = preprocessing.scale(tr_data)


	#SETUP CLASSIFIER
	trndata = ClassificationDataSet(len(tr_data[0]))
	for j in range(len(tr_data)):
	    trndata.addSample(tr_data[j], tr_labels[j])

	trndata._convertToOneOfMany()
	fnn = buildNetwork(trndata.indim, 20, trndata.outdim, outclass=SoftmaxLayer )
	trainer = BackpropTrainer( fnn, dataset=trndata, momentum=0.1, weightdecay=0.01)
	for i in range(20):
		trainer.trainEpochs( 1 )

	for (slot, weakseed, strongseed) in slot_map[year]:
		team1 = CumulativeStat.find_by_team_year(year, seed_map[year][weakseed])
		team2 = CumulativeStat.find_by_team_year(year, seed_map[year][strongseed])

		rpi_diff =  team2.get_rank('RPI') - team1.get_rank('RPI')

		if rpi_diff > 0:
			high_seed = team1
			low_seed = team2
		else:
			high_seed = team2
			low_seed = team1

		high_seed_name = high_seed.play.team_year.team.name
		low_seed_name = low_seed.play.team_year.team.name

		tst_data = high_seed.selected_features() - low_seed.selected_features()
		tst_data = np.nan_to_num(np.divide((tst_data - mean), std))

		#PREDICT WITH CLASSIFIER
		answer = np.argmax(fnn.activate(tst_data))
		result = answer == 1

		#Update seed_map for next round
		if result == True:
			seed_map[year][slot] = low_seed_name
		else:
			seed_map[year][slot] = high_seed_name

		#Determine if prediction was correct or not by looking for game with those teams
		potential_game = Game.find_by_teams_year(year, low_seed_name, high_seed_name)
		if potential_game is not None and potential_game.winner().play.team_year.team.name == seed_map[year][slot]:
			correct = True
		else:
			correct = False

		if correct:
			correct_dict[year].append(1)
			round_num = int(slot[1])
			espn_score = 2**(round_num-1)
			score_dict[year].append(espn_score)
		else:
			correct_dict[year].append(0)

		print "%s %s v %s -- %s" % (slot, seed_map[year][weakseed], seed_map[year][strongseed], seed_map[year][slot])

for year in years:
	print "%i ESPN Score: %i" % (year, 10*sum(score_dict[year]))
	print "%i Percent Correct: %f" % (year, float(sum(correct_dict[year]))/float(len(correct_dict[year])))


